"""Grade 1 English · Q1 W8 D2 · Sharing and Helping Hands.

Source: old Drive lesson SPT/ENG/GRADE1/Q1/WEEK8/DAY2/INTERACTIVE/index.html
("Sharing and Helping Hands — Action Words & Kindness"; words share, help,
care; check: when a classmate needs help, lend a helping hand). No DepEd
deck/script exists for Week 8; week verse "A friend loves at all times."
(Proverbs 17:17).
Objectives: learn kind action words (share, help, care, take turns); listen
to "Lino's Crayons" and tell who helped and how; say how I can help a friend.
Spiral review: friend, greet (W8 D1), thank you (W1 D2).
"""

LINO = 'Lino (Filipino boy, 6, the new classmate: curly black hair, green T-shirt, brown shorts, small red school bag)'
ROOM = 'a bright Filipino Grade 1 classroom with a green chalkboard, small wooden desks and paper flowers on the wall'

LESSON = {'grade': 1,
 'quarter': 1,
 'week': 8,
 'day': 2,
 'title': 'Sharing and Helping Hands',
 'source': 'Old Drive lesson Q1 W8 D2 "Sharing and Helping Hands" (no DepEd deck found); verse Proverbs 17:17',
 'bg': 'media/image10.jpg',
 'next': '../../DAY3/INTERACTIVE/index.html',
 'slides': [{'type': 'cover',
             'pose': 'waving.png',
             'goal': 1,
             'title': 'Sharing and Helping Hands',
             'goals': ['Say 4 kind action words', 'Tell who helped in the story', 'Say how I help a friend'],
             'say': 'Hello again, my friend! (pause) Yesterday, Tala met her new friend Lino. (pause) Today, we '
                    'learn to share and help!',
             'art': {'file': 'media/art/cover-helping.png',
                     'prompt': 'Tala (Filipino girl, 6) and ' + LINO + ' at a classroom desk: Tala hands Lino a '
                               'crayon with a smile while Lino holds out his hand. ' + ROOM + '.',
                     'scene': True}},
            {'id': 'words',
             'type': 'cards',
             'pose': 'pointing.png',
             'goal': 1,
             'title': '4 Kind Action Words',
             'say': 'Good friends do kind things. (pause) Listen. (pause) Then tap each picture and say it with me!',
             'yourTurn': 'Tap each picture!',
             'items': [{'word': 'share',
                        'sub': 'give some to a friend',
                        'art': {'file': 'media/art/word-share.png',
                                'prompt': 'Tala (Filipino girl, 6) breaking her pandesal bread in half and giving '
                                          'one half to ' + LINO + '; both smile.'},
                        'say': 'Share. (pause) When we share, we give some to a friend.'},
                       {'word': 'help',
                        'sub': 'do something for others',
                        'art': {'file': 'media/art/word-help.png',
                                'prompt': 'Tala (Filipino girl, 6) kneeling to help ' + LINO + ' pick up crayons '
                                          'that fell on the floor.'},
                        'say': 'Help. (pause) When we help, we do something for others.'},
                       {'word': 'care',
                        'sub': 'be gentle and kind',
                        'art': {'file': 'media/art/word-care.png',
                                'prompt': 'Tala (Filipino girl, 6) gently putting her hand on the shoulder of '
                                          'Bunso, who has a small scraped knee, asking if he is okay.'},
                        'say': 'Care. (pause) When we care, we are gentle and kind. (pause) Are you okay?'},
                       {'word': 'take turns',
                        'sub': 'you, then me',
                        'art': {'file': 'media/art/word-take-turns.png',
                                'prompt': 'Two children, Tala (Filipino girl, 6) and ' + LINO + ', at a playground '
                                          'slide: Lino slides down while Tala waits at the ladder with a smile.'},
                        'say': 'Take turns. (pause) You go first, then me!'}],
             'bridge': 'Lino is our friend now. Let us learn how to be kind to him.'},
            {'id': 'act',
             'type': 'act',
             'pose': 'clapping.png',
             'goal': 1,
             'title': 'Show Me Helping Hands!',
             'say': 'Stand up! (pause) Let us use our helping hands. (pause) Do it with me, then tap.',
             'yourTurn': 'Do it, then tap!',
             'cmds': [{'word': 'Share!', 'sub': 'Give with two hands.', 'pose': 'TALA/giving.png',
                       'say': 'Share! (pause) Hold out your hands and give.'},
                      {'word': 'Help!', 'sub': 'Bend down and pick up.', 'pose': 'TALA/reaching.png',
                       'say': 'Help! (pause) Bend down and pick it up.'},
                      {'word': 'Care!', 'sub': 'Give a gentle hug.', 'pose': 'TALA/hugging.png',
                       'say': 'Care! (pause) Give yourself a gentle hug.'},
                      {'word': 'Take turns!', 'sub': 'You, then me.', 'pose': 'TALA/pointing.png',
                       'say': 'Take turns! (pause) Point to a friend. You, then me!'}],
             'bridge': 'You know the words! Now let us move our helping hands.'},
            {'id': 'find',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 1,
             'title': 'Listen and Tap!',
             'say': 'Listen carefully. (pause) Tap the right picture.',
             'yourTurn': 'Tap the right picture!',
             'rounds': [{'ask': 'Tap: share',
                         'askSay': 'Where is share? Tap it!',
                         'choices': [{'word': 'share', 'ok': True,
                                      'art': {'file': 'media/art/word-share.png',
                                              'prompt': 'Tala (Filipino girl, 6) breaking her pandesal bread in half '
                                                        'and giving one half to ' + LINO + '; both smile.'}},
                                     {'word': 'take turns',
                                      'art': {'file': 'media/art/word-take-turns.png',
                                              'prompt': 'Two children, Tala (Filipino girl, 6) and ' + LINO + ', at '
                                                        'a playground slide: Lino slides down while Tala waits at '
                                                        'the ladder with a smile.'}},
                                     {'word': 'care',
                                      'art': {'file': 'media/art/word-care.png',
                                              'prompt': 'Tala (Filipino girl, 6) gently putting her hand on the '
                                                        'shoulder of Bunso, who has a small scraped knee, asking if '
                                                        'he is okay.'}}]},
                        {'ask': 'Tap: help',
                         'askSay': 'Where is help? Tap it!',
                         'choices': [{'word': 'care',
                                      'art': {'file': 'media/art/word-care.png',
                                              'prompt': 'Tala (Filipino girl, 6) gently putting her hand on the '
                                                        'shoulder of Bunso, who has a small scraped knee, asking if '
                                                        'he is okay.'}},
                                     {'word': 'help', 'ok': True,
                                      'art': {'file': 'media/art/word-help.png',
                                              'prompt': 'Tala (Filipino girl, 6) kneeling to help ' + LINO + ' pick '
                                                        'up crayons that fell on the floor.'}},
                                     {'word': 'share',
                                      'art': {'file': 'media/art/word-share.png',
                                              'prompt': 'Tala (Filipino girl, 6) breaking her pandesal bread in half '
                                                        'and giving one half to ' + LINO + '; both smile.'}}]}],
             'bridge': 'Great moving! Now use your ears.'},
            {'id': 's1',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': "Story: Lino's Crayons",
             'page': 'Page 1',
             'lines': ['It is art time.', 'Lino opens his crayon box.', 'He wants to draw a sun.'],
             'say': "Story time! (pause) Our story is, Lino's Crayons. (pause) It is art time. (pause) Lino opens "
                    'his crayon box. (pause) He wants to draw a big sun.',
             'art': {'file': 'media/art/story-art-time.png',
                     'prompt': 'Art time in ' + ROOM + ': ' + LINO + ' happily opening a box of crayons at his desk, '
                               'a blank paper in front of him; Tala (Filipino girl, 6) draws at the next desk.',
                     'scene': True},
             'bridge': 'You know the kind words. Now let us see them in a story!'},
            {'id': 's2',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': "Story: Lino's Crayons",
             'page': 'Page 2',
             'lines': ['Oh no! The box falls.', 'The crayons roll everywhere.', 'The yellow crayon breaks!'],
             'say': 'Oh no! (pause) The box falls down. (pause) The crayons roll everywhere. (pause) And the '
                    'yellow crayon breaks! (pause) Lino is sad.',
             'art': {'file': 'media/art/story-crayons-fall.png',
                     'prompt': LINO + ' looking sad as his crayon box falls off the desk; colourful crayons roll '
                               'across the classroom floor and a yellow crayon lies broken in two. ' + ROOM + '.',
                     'scene': True},
             'bridge': 'But then, something happens.'},
            {'id': 'mid',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 2,
             'title': 'Quick! What Can Tala Do?',
             'say': 'Quick question! (pause) Lino needs help.',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'What should Tala do?',
                         'askSay': 'The crayons fell. (pause) What should Tala do?',
                         'choices': [{'word': 'help pick up', 'ok': True,
                                      'art': {'file': 'media/art/word-help.png',
                                              'prompt': 'Tala (Filipino girl, 6) kneeling to help ' + LINO + ' pick '
                                                        'up crayons that fell on the floor.'}},
                                     {'word': 'laugh at him', 'pose': 'TALA/laughing.png'},
                                     {'word': 'walk away', 'pose': 'TALA/walking.png'}],
                         'yes': 'Yes! Help pick them up.',
                         'yesSay': 'Yes! A good friend helps. (pause) Let us see what Tala does!'}],
             'bridge': 'Lino needs help. What should Tala do?'},
            {'id': 's3',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': "Story: Lino's Crayons",
             'page': 'Page 3',
             'lines': ['Tala and Bunso help.', 'They pick up the crayons.', 'Tala shares her yellow crayon.'],
             'say': 'Tala and Bunso come to help. (pause) They pick up all the crayons. (pause) Then Tala shares '
                    'her yellow crayon. (pause) Here, Lino!',
             'art': {'file': 'media/art/story-help-share.png',
                     'prompt': 'Tala (Filipino girl, 6) and Bunso kneeling on the classroom floor picking up '
                               'crayons with ' + LINO + '; Tala holds out her own yellow crayon to Lino with a '
                               'smile.',
                     'scene': True},
             'bridge': 'Look who comes to help!'},
            {'id': 's4',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': "Story: Lino's Crayons",
             'page': 'Page 4',
             'lines': ['"Thank you, Tala!" says Lino.', 'They take turns with the crayon.', 'They draw a big sun!'],
             'say': 'Lino smiles. (pause) Thank you, Tala! (pause) They take turns with the yellow crayon. '
                    '(pause) Together, they draw a big, bright sun!',
             'art': {'file': 'media/art/story-big-sun.png',
                     'prompt': 'Tala (Filipino girl, 6), Bunso and ' + LINO + ' proudly holding up one big drawing '
                               'of a bright yellow sun they made together, everyone smiling. ' + ROOM + '.',
                     'scene': True},
             'bridge': 'How does the story end?'},
            {'id': 'check',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 2,
             'title': 'Think About the Story',
             'say': 'Let us think about the story.',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'Who helped Lino?',
                         'askSay': 'Who helped Lino pick up the crayons?',
                         'choices': [{'word': 'Tala and Bunso', 'ok': True,
                                      'art': {'file': 'media/art/story-help-share.png',
                                              'prompt': 'Tala (Filipino girl, 6) and Bunso kneeling on the '
                                                        'classroom floor picking up crayons with ' + LINO + '; Tala '
                                                        'holds out her own yellow crayon to Lino with a smile.',
                                              'scene': True}},
                                     {'word': 'Nanay', 'pose': 'NANAY/waving.png'},
                                     {'word': 'Tatay', 'pose': 'TATAY/waving.png'}],
                         'yes': 'Yes! Tala and Bunso!',
                         'yesSay': 'Yes! Tala and Bunso helped Lino.'},
                        {'ask': 'What did Tala share?',
                         'askSay': 'What did Tala share with Lino?',
                         'choices': [{'word': 'a yellow crayon', 'ok': True,
                                      'art': {'file': 'media/art/yellow-crayon.png',
                                              'prompt': 'One bright yellow wax crayon lying on a desk.'}},
                                     {'word': 'a ball',
                                      'art': {'file': 'media/art/ball.png',
                                              'prompt': 'One red and blue rubber ball.'}},
                                     {'word': 'a book', 'pose': 'TALA/holding_book.png'}],
                         'yes': 'Yes! A yellow crayon!',
                         'yesSay': 'Yes! Tala shared her yellow crayon.'},
                        {'ask': 'What did Lino say?',
                         'askSay': 'What did Lino say to Tala?',
                         'choices': [{'word': 'Thank you!', 'ok': True,
                                      'art': {'file': 'media/art/lino-thank-you.png',
                                              'prompt': LINO + ' smiling and bowing a little with his hand on his '
                                                        'heart, saying thank you.'}},
                                     {'word': 'Go away!',
                                      'art': {'file': 'media/art/lino-shy.png',
                                              'prompt': LINO + ', looking shy and a little sad, eyes down, hands '
                                                        'holding his bag strap. Full body.'}}],
                         'yes': 'Yes! Thank you!',
                         'yesSay': 'Yes! Lino said, Thank you, Tala! (pause) That is a kind word.'}],
             'bridge': 'Friends help and share!'},
            {'id': 'order',
             'type': 'order',
             'pose': 'thinking.png',
             'goal': 2,
             'title': 'What Happened First?',
             'say': 'Tap the pictures in order. (pause) First. (pause) Next. (pause) Last.',
             'yourTurn': 'Tap what happened first!',
             'slots': ['First', 'Next', 'Last'],
             'items': [{'word': 'The crayons fell.',
                        'say': 'First, the crayons fell.',
                        'art': {'file': 'media/art/story-crayons-fall.png',
                                'prompt': LINO + ' looking sad as his crayon box falls off the desk; colourful '
                                          'crayons roll across the classroom floor and a yellow crayon lies broken '
                                          'in two. ' + ROOM + '.',
                                'scene': True}},
                       {'word': 'Tala helped and shared.',
                        'say': 'Next, Tala helped and shared.',
                        'art': {'file': 'media/art/story-help-share.png',
                                'prompt': 'Tala (Filipino girl, 6) and Bunso kneeling on the classroom floor picking '
                                          'up crayons with ' + LINO + '; Tala holds out her own yellow crayon to '
                                          'Lino with a smile.',
                                'scene': True}},
                       {'word': 'They drew a sun.',
                        'say': 'Last, they drew a big sun together.',
                        'art': {'file': 'media/art/story-big-sun.png',
                                'prompt': 'Tala (Filipino girl, 6), Bunso and ' + LINO + ' proudly holding up one big '
                                          'drawing of a bright yellow sun they made together, everyone smiling. '
                                          + ROOM + '.',
                                'scene': True}}],
             'ask': ['What happened first?', 'What happened next?', 'What happened last?'],
             'yes': 'First, next, last. You did it!',
             'yesSay': 'First, next, last! (pause) You told the whole story!',
             'bridge': 'Can you remember the whole story?'},
            {'id': 'i-can-help',
             'type': 'sentence',
             'pose': 'point_self.png',
             'goal': 3,
             'title': 'How Can YOU Help?',
             'say': 'How can you be a helping hand? (pause) Tap one. (pause) Then say it with me.',
             'yourTurn': 'Tap one and say it!',
             'pre': 'I can',
             'post': '.',
             'options': [{'word': 'share my snack',
                          'art': {'file': 'media/art/word-share.png',
                                  'prompt': 'Tala (Filipino girl, 6) breaking her pandesal bread in half and giving '
                                            'one half to ' + LINO + '; both smile.'}},
                         {'word': 'help pick up toys',
                          'art': {'file': 'media/art/help-toys.png',
                                  'prompt': 'Bunso (5) and Tala (Filipino girl, 6) putting toy blocks back into a '
                                            'basket together in the living room.'}},
                         {'word': 'take turns',
                          'art': {'file': 'media/art/word-take-turns.png',
                                  'prompt': 'Two children, Tala (Filipino girl, 6) and ' + LINO + ', at a playground '
                                            'slide: Lino slides down while Tala waits at the ladder with a smile.'}}],
             'bridge': 'Tala was a helping hand. You can be one too!'},
            {'id': 'talk',
             'type': 'talk',
             'pose': 'talking.png',
             'goal': 3,
             'title': 'Your Turn to Talk!',
             'say': 'Tell me how you help a friend. (pause) Say: I help my friend. I share my crayons. (pause) '
                    'Your turn!',
             'yourTurn': 'Say it out loud!',
             'frame': 'I help my friend. I share my ____.',
             'example': {'label': 'Tala says', 'text': 'I help my friend. I share my crayons.'},
             'art': {'file': 'media/art/story-help-share.png',
                     'prompt': 'Tala (Filipino girl, 6) and Bunso kneeling on the classroom floor picking up '
                               'crayons with ' + LINO + '; Tala holds out her own yellow crayon to Lino with a '
                               'smile.',
                     'scene': True},
             'bridge': 'Now say it all by yourself!'},
            {'id': 'verse',
             'type': 'verse',
             'pose': 'praying.png',
             'verse': 'A friend loves at all times.',
             'ref': 'Proverbs 17:17',
             'meaning': 'Friends help and share, even on sad days.',
             'say': 'Our Bible verse is, (pause) A friend loves at all times. (pause) Lino had a sad day. '
                    '(pause) Tala still helped him!',
             'verseSay': 'A friend loves at all times. (pause) Proverbs seventeen, verse seventeen.',
             'art': {'file': 'media/art/verse-friends.png',
                     'prompt': 'Tala (Filipino girl, 6), ' + LINO + ' and Bunso walking out of the school gate '
                               'together holding hands and smiling, warm afternoon light.',
                     'scene': True},
             'bridge': 'Tala helped Lino on a sad day. The Bible tells us why.'},
            {'id': 'done',
             'type': 'celebrate',
             'pose': 'clapping.png',
             'title': 'You Have Helping Hands!',
             'recap': ['I know: share, help, care, take turns.',
                       'Tala and Bunso helped Lino.',
                       'I can say how I help.'],
             'say': 'Hooray! (pause) You learned four kind words. (pause) You told who helped Lino. (pause) And '
                    'you said how you help. (pause) Tomorrow, we listen and learn together!',
             'bridge': 'What a kind day we had!'}]}
