"""Grade 1 English · Q1 W2 D3 · Naming Words for People.

Source: Drive SPT/ENG/GRADE1/Q1/WEEK2/DAY3/INTERACTIVE/index.html ("Naming Words for People",
Proverbs 22:6; no LANG1Q1W2DAY3 DepEd deck exists in Drive). Verse slide: LANG1-Q1W2-DAY3.png.
Objectives: name family members with naming words (mom, dad, older sister, older brother,
grandma, grandpa, youngest child / Nanay, Tatay, Ate, Kuya, Lola, Lolo, Bunso); sing the family
song (tune: Leron-Leron Sinta); tell common naming words (small letter: mom) from special
names (capital letter: Lita); say "This is my ___." and "My mom's name is ___."
Specific names from the source: Lita (mom), Rico (dad), Hinhin (older sister). The source's
older brother "Sig" is Kuya Gas, the series character.
"""

FAMILY_COVER = {'file': 'media/art/family-cover.png',
                'prompt': "Tala (Filipino girl, 6) and her whole family standing together in a cosy living room, "
                          "all smiling and waving: Nanay, Tatay, Lola (grey hair, glasses, pink dress), Lolo (grey "
                          "hair, white polo shirt, walking cane), Ate Hinhin (10), Kuya Gas (11) and Bunso (5).",
                'scene': True}

FAMILY_DINNER = {'file': 'media/art/family-dinner.png',
                 'prompt': 'Tala (Filipino girl, 6) and her whole family eating dinner together at one long wooden '
                           'table: Nanay, Tatay, Lola, Lolo, Ate Hinhin, Kuya Gas and Bunso, a pot of adobo and '
                           'rice in the middle, everyone laughing happily.',
                 'scene': True}

LOLO_CARD = {'file': 'media/art/lolo-card.png',
             'prompt': 'Lolo, a kind Filipino grandfather with grey hair, round glasses, white polo shirt and a '
                       'wooden walking cane, smiling warmly, full body.'}

LOLA_IMG = 'media/image14.png'      # grandma reading a story book to a little girl

LESSON = {'grade': 1,
 'quarter': 1,
 'week': 2,
 'day': 3,
 'title': 'Naming Words for People',
 'source': 'Old Drive lesson W2 D3 "Naming Words for People" (Proverbs 22:6); no DepEd deck found',
 'bg': 'media/image5.jpg',
 'next': '../../DAY4/INTERACTIVE/index.html',
 'slides': [{'type': 'cover',
             'pose': 'waving.png',
             'goal': 1,
             'title': 'Naming Words for People',
             'goals': ['I can name my family', 'I can sing a family song', 'I can tell special names'],
             'say': 'Hello, my friend! (pause) Yesterday we played Simon Says. (pause) We asked who, what and '
                    'where about Katkat. (pause) Today we answer WHO. (pause) Words for people are naming words! '
                    '(pause) Come and meet my family!',
             'art': FAMILY_COVER},
            {'id': 'fam1',
             'type': 'cards',
             'pose': 'pointing.png',
             'goal': 1,
             'title': 'My Family',
             'say': 'A naming word tells who a person is. (pause) Tap each picture. (pause) Say the word with me!',
             'yourTurn': 'Tap each picture!',
             'items': [{'word': 'mom', 'sub': 'Nanay', 'pose': 'NANAY/hugging.png',
                        'say': 'Mom. (pause) Nanay. (pause) My mom cares for our family.'},
                       {'word': 'dad', 'sub': 'Tatay', 'pose': 'TATAY/waving.png',
                        'say': 'Dad. (pause) Tatay. (pause) My dad keeps us safe.'},
                       {'word': 'older sister', 'sub': 'Ate', 'pose': 'ATE/waving.png',
                        'say': 'Older sister. (pause) Ate. (pause) She helps me every day.'},
                       {'word': 'older brother', 'sub': 'Kuya', 'pose': 'KUYA/waving.png',
                        'say': 'Older brother. (pause) Kuya. (pause) He plays with me.'}],
             'bridge': 'Who is in my family? Let us see!'},
            {'id': 'fam2',
             'type': 'cards',
             'pose': 'hugging.png',
             'goal': 1,
             'title': 'More Family Words',
             'say': 'Here are three more family words. (pause) Tap each one. (pause) Say it with me!',
             'yourTurn': 'Tap each picture!',
             'items': [{'word': 'grandma', 'sub': 'Lola', 'img': LOLA_IMG,
                        'say': 'Grandma. (pause) Lola. (pause) She is the mother of my mom or dad.'},
                       {'word': 'grandpa', 'sub': 'Lolo', 'art': LOLO_CARD,
                        'say': 'Grandpa. (pause) Lolo. (pause) He is the father of my mom or dad.'},
                       {'word': 'youngest child', 'sub': 'Bunso', 'pose': 'BUNSO/waving.png',
                        'say': 'Youngest child. (pause) Bunso. (pause) He is the baby of our family!'}],
             'bridge': 'My family is big! There are more people to meet.'},
            {'id': 'find',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 1,
             'title': 'Listen and Tap!',
             'say': 'Listen to the naming word. (pause) Tap the right person!',
             'yourTurn': 'Tap the right person!',
             'rounds': [{'ask': 'Tap: older brother',
                         'askSay': 'Where is the older brother? (pause) Tap Kuya!',
                         'choices': [{'word': 'older sister', 'pose': 'ATE/waving.png'},
                                     {'word': 'older brother', 'pose': 'KUYA/waving.png', 'ok': True},
                                     {'word': 'mom', 'pose': 'NANAY/hugging.png'}],
                         'yes': 'Yes! Kuya is my older brother.',
                         'yesSay': 'Yes! Kuya is my older brother.'},
                        {'ask': 'Tap: grandpa',
                         'askSay': 'Where is grandpa? (pause) Tap Lolo!',
                         'choices': [{'word': 'dad', 'pose': 'TATAY/waving.png'},
                                     {'word': 'youngest child', 'pose': 'BUNSO/waving.png'},
                                     {'word': 'grandpa', 'ok': True, 'art': LOLO_CARD}],
                         'yes': 'Yes! Lolo is my grandpa.',
                         'yesSay': 'Yes! Lolo is my grandpa.'},
                        {'ask': 'Tap: mom',
                         'askSay': 'Where is mom? (pause) Tap Nanay!',
                         'choices': [{'word': 'mom', 'pose': 'NANAY/hugging.png', 'ok': True},
                                     {'word': 'grandma', 'img': LOLA_IMG},
                                     {'word': 'older sister', 'pose': 'ATE/waving.png'}],
                         'yes': 'Yes! Nanay is my mom.',
                         'yesSay': 'Yes! Nanay is my mom.'}],
             'bridge': 'You met my whole family! Can you find them?'},
            {'id': 'song',
             'type': 'chant',
             'pose': 'clapping.png',
             'goal': 2,
             'title': 'The Family Song',
             'say': 'Let us sing to the tune of Leron-Leron Sinta. (pause) Listen first. (pause) Then tap a line '
                    'and sing!',
             'yourTurn': 'Tap a line and sing!',
             'allLabel': 'Sing it all!',
             'lines': [{'text': 'Mom and Dad, truly caring!'},
                       {'text': 'Older sister and brother, always happy!'},
                       {'text': 'Grandma and Grandpa, very loving!'},
                       {'text': 'That is why we all eat together!'}],
             'art': FAMILY_DINNER,
             'bridge': 'You know all the family words. Now let us sing them!'},
            {'id': 's1',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 1,
             'title': 'Dinner at Tala’s House',
             'page': 'Page 1',
             'lines': ['It is dinner time.', 'Mom cooks adobo.', 'Dad and Kuya set the table.'],
             'say': 'Story time! (pause) It is dinner time at my house. (pause) Mom cooks yummy adobo. (pause) '
                    'Dad and Kuya set the table.',
             'art': {'file': 'media/art/dinner-cooking.png',
                     'prompt': 'Evening in a Filipino home kitchen: Nanay stirring a pot of adobo on the stove, '
                               'Tatay and Kuya Gas (11) putting plates and spoons on a wooden table, Tala (6) '
                               'watching happily.',
                     'scene': True},
             'bridge': 'The song says we eat together. Let us see my family at dinner!'},
            {'id': 's2',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 1,
             'title': 'Dinner at Tala’s House',
             'page': 'Page 2',
             'lines': ['Grandma sits down.', 'But one chair is empty!', '"Where is Grandpa?" asks Ate.'],
             'say': 'Grandma sits down. (pause) Ate and Bunso sit down. (pause) But one chair is empty! (pause) '
                    'Where is Grandpa? asks Ate.',
             'art': {'file': 'media/art/empty-chair.png',
                     'prompt': 'Tala’s family at the dinner table: Lola, Nanay, Tatay, Ate Hinhin, Kuya Gas, Bunso '
                               'and Tala sitting; one empty chair at the head of the table; Ate Hinhin pointing at '
                               'the empty chair, everyone looking puzzled.',
                     'scene': True},
             'bridge': 'Everyone comes to the table. But wait!'},
            {'id': 'mid',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 1,
             'title': 'Who Is Missing?',
             'say': 'Quick question! (pause) Remember, who is for a person.',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'WHO is not at the table?',
                         'askSay': 'Who is not at the table?',
                         'choices': [{'word': 'grandpa', 'ok': True, 'art': LOLO_CARD},
                                     {'word': 'grandma', 'img': LOLA_IMG},
                                     {'word': 'mom', 'pose': 'NANAY/hugging.png'}],
                         'yes': 'Yes! Grandpa is missing.',
                         'yesSay': 'Yes! Grandpa is missing. (pause) Where can he be?'}],
             'bridge': 'Hmm. Somebody is missing.'},
            {'id': 's3',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 1,
             'title': 'Dinner at Tala’s House',
             'page': 'Page 3',
             'lines': ['Bunso looks in the living room.', 'Grandpa is asleep in his chair!',
                       '"Lolo, it is time to eat!"'],
             'say': 'Bunso looks in the living room. (pause) There is Grandpa! (pause) He is asleep in his big '
                    'chair. (pause) Bunso hugs him. (pause) Lolo, it is time to eat!',
             'art': {'file': 'media/art/bunso-finds-lolo.png',
                     'prompt': 'In a cosy living room, Lolo (grey hair, glasses) asleep in a big armchair with a '
                               'newspaper on his lap; Bunso (5) gently hugging his arm and smiling to wake him.',
                     'scene': True},
             'bridge': 'Let us find Grandpa!'},
            {'id': 's4',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': 'Dinner at Tala’s House',
             'page': 'Page 4',
             'lines': ['Now we all eat together.', 'We sing our family song.', 'A family helps each other.'],
             'say': 'Grandpa laughs and comes to the table. (pause) Now we all eat together! (pause) We sing our '
                    'family song. (pause) A family helps each other.',
             'art': FAMILY_DINNER,
             'bridge': 'Grandpa wakes up with a smile.'},
            {'id': 'story-check',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 1,
             'title': 'Think About the Story',
             'say': 'Let us think about the story. (pause) Listen to each question.',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'WHO found Grandpa?',
                         'askSay': 'Who found Grandpa?',
                         'choices': [{'word': 'youngest child', 'pose': 'BUNSO/waving.png', 'ok': True},
                                     {'word': 'dad', 'pose': 'TATAY/waving.png'}],
                         'yes': 'Yes! Bunso found Grandpa.',
                         'yesSay': 'Yes! Bunso, the youngest child, found Grandpa.'},
                        {'ask': 'WHO cooked the adobo?',
                         'askSay': 'Who cooked the adobo?',
                         'choices': [{'word': 'older brother', 'pose': 'KUYA/waving.png'},
                                     {'word': 'mom', 'pose': 'NANAY/hugging.png', 'ok': True}],
                         'yes': 'Yes! Mom cooked the adobo.',
                         'yesSay': 'Yes! Mom cooked the adobo.'}],
             'bridge': 'That is the end of the story. Let us answer WHO questions!'},
            {'id': 'common',
             'type': 'cards',
             'pose': 'pointing.png',
             'goal': 3,
             'title': 'Common Names',
             'say': 'Mom, dad, sister, brother. (pause) These are common names. (pause) Many people are called '
                    'mom! (pause) We write them with small letters.',
             'yourTurn': 'Tap each common name!',
             'items': [{'word': 'mom', 'sub': 'small m', 'pose': 'NANAY/hugging.png',
                        'say': 'mom. (pause) Small letter m.'},
                       {'word': 'dad', 'sub': 'small d', 'pose': 'TATAY/waving.png',
                        'say': 'dad. (pause) Small letter d.'},
                       {'word': 'sister', 'sub': 'small s', 'pose': 'ATE/waving.png',
                        'say': 'sister. (pause) Small letter s.'},
                       {'word': 'brother', 'sub': 'small b', 'pose': 'KUYA/waving.png',
                        'say': 'brother. (pause) Small letter b.'}],
             'bridge': 'Every person has two kinds of naming words.'},
            {'id': 'special',
             'type': 'cards',
             'pose': 'showing.png',
             'goal': 3,
             'title': 'Special Names',
             'say': 'Now, special names! (pause) A special name is for ONE person. (pause) It starts with a big '
                    'capital letter.',
             'yourTurn': 'Tap each special name!',
             'items': [{'word': 'Lita', 'sub': 'my mom • big L', 'pose': 'NANAY/hugging.png',
                        'say': 'Lita. (pause) My mom’s name is Lita. (pause) Big letter L.'},
                       {'word': 'Rico', 'sub': 'my dad • big R', 'pose': 'TATAY/waving.png',
                        'say': 'Rico. (pause) My dad’s name is Rico. (pause) Big letter R.'},
                       {'word': 'Hinhin', 'sub': 'my sister • big H', 'pose': 'ATE/waving.png',
                        'say': 'Hinhin. (pause) My sister’s name is Hinhin. (pause) Big letter H.'},
                       {'word': 'Gas', 'sub': 'my brother • big G', 'pose': 'KUYA/waving.png',
                        'say': 'Gas. (pause) My brother’s name is Gas. (pause) Big letter G.'}],
             'bridge': 'Mom is a common name. But my mom has her own special name!'},
            {'id': 'which-name',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 3,
             'title': 'Common or Special?',
             'say': 'Same person, two names! (pause) Listen and tap.',
             'yourTurn': 'Tap the right name!',
             'rounds': [{'ask': 'Tap the SPECIAL name.',
                         'askSay': 'Which one is a special name?',
                         'choices': [{'word': 'sister', 'pose': 'ATE/waving.png'},
                                     {'word': 'Hinhin', 'pose': 'ATE/waving.png', 'ok': True}],
                         'yes': 'Yes! Hinhin. Big letter H.',
                         'yesSay': 'Yes! Hinhin is a special name. (pause) It starts with a big H.',
                         'hintSay': 'A special name is for one person. It starts with a big letter.'},
                        {'ask': 'Which starts with a BIG letter?',
                         'askSay': 'Which name starts with a big capital letter?',
                         'choices': [{'word': 'Rico', 'pose': 'TATAY/waving.png', 'ok': True},
                                     {'word': 'dad', 'pose': 'TATAY/waving.png'}],
                         'yes': 'Yes! Rico. Big letter R.',
                         'yesSay': 'Yes! Rico starts with a big R.'},
                        {'ask': 'Tap the COMMON name.',
                         'askSay': 'Which one is a common name, with a small letter?',
                         'choices': [{'word': 'Lita', 'pose': 'NANAY/hugging.png'},
                                     {'word': 'mom', 'pose': 'NANAY/hugging.png', 'ok': True}],
                         'yes': 'Yes! mom. Small letter m.',
                         'yesSay': 'Yes! Mom is a common name. (pause) Small letter m.'}],
             'bridge': 'Let us check: common or special?'},
            {'id': 'this-is',
             'type': 'sentence',
             'pose': 'point_self.png',
             'goal': 1,
             'title': 'This Is My...',
             'say': 'Now show your family! (pause) Tap a naming word. (pause) Then say the sentence with me.',
             'yourTurn': 'Tap one and say it!',
             'pre': 'This is my',
             'post': '.',
             'options': [{'word': 'mom', 'pose': 'NANAY/hugging.png'},
                         {'word': 'dad', 'pose': 'TATAY/waving.png'},
                         {'word': 'grandma', 'img': LOLA_IMG},
                         {'word': 'older brother', 'pose': 'KUYA/waving.png'}],
             'bridge': 'You know common and special names. Now build a sentence!'},
            {'id': 'talk',
             'type': 'talk',
             'pose': 'talking.png',
             'goal': 3,
             'title': 'Tell Me About Your Family!',
             'say': 'Now tell me about your family. (pause) What is your mom’s special name? (pause) Say: My '
                    'mom’s name is Lita. (pause) Use your mom’s name!',
             'yourTurn': 'Say your mom’s name!',
             'frame': 'My mom’s name is ____.',
             'example': {'label': 'Tala says', 'text': 'My mom’s name is Lita.'},
             'art': FAMILY_COVER,
             'bridge': 'You can say who is in your family. Now say a special name!'},
            {'id': 'verse',
             'type': 'verse',
             'pose': 'praying.png',
             'verse': 'Train up a child in the way he should go.',
             'ref': 'Proverbs 22:6',
             'meaning': 'My family teaches me the good way.',
             'say': 'Our Bible verse is, (pause) Train up a child in the way he should go. (pause) Our family '
                    'teaches us the good way. (pause) We love and listen to them.',
             'verseSay': 'Train up a child in the way he should go. (pause) Proverbs twenty-two, verse six.',
             'art': {'file': 'media/art/verse-family.png',
                     'prompt': 'Lolo and Lola gently teaching Tala (6) and Bunso (5) to fold their hands and pray '
                               'before dinner, the family table behind them, warm lamp light.',
                     'scene': True},
             'bridge': 'Our family loves us and teaches us. The Bible tells us this too.'},
            {'id': 'done',
             'type': 'celebrate',
             'pose': 'clapping.png',
             'title': 'Super Family Words!',
             'recap': ['I can name my family.', 'I can sing the family song.', 'Special names have big letters.'],
             'say': 'Hooray! (pause) You named my whole family. (pause) You sang the family song. (pause) And you '
                    'know special names start with big letters. (pause) Tomorrow we meet more family: uncles, '
                    'aunts and cousins!',
             'bridge': 'What a happy family day!'}]}
