"""Grade 1 English · Q1 W1 D3 · Songs and Stories.

Source: LANG1Q1W1DAY3NARRATIONSCRIPT (Nursery Rhymes and Stories, Exodus 20:12).
Objectives: sing a song and name vegetables, sing and move, listen to two
stories and tell what they teach (be kind and patient, help at home).
"""

LESSON = {'grade': 1,
 'quarter': 1,
 'week': 1,
 'day': 3,
 'title': 'Songs and Stories',
 'source': 'LANG1Q1W1DAY3NARRATIONSCRIPT — Nursery Rhymes and Stories (Exodus 20:12)',
 'bg': 'media/image1.jpg',
 'next': '../../DAY4/INTERACTIVE/index.html',
 'slides': [{'type': 'cover',
             'pose': 'waving.png',
             'goal': 1,
             'title': 'Songs and Stories',
             'goals': ['Sing and name vegetables', 'Sing and move my body', 'Listen to two stories'],
             'say': 'Good morning, my friend! (pause) Yesterday we got ready for school. (pause) Today we sing '
                    'songs. (pause) And we listen to stories!',
             'art': {'file': 'media/art/cover.png',
                     'prompt': 'Tala (6), Bunso (5) and Ate Hinhin (10) sitting together on a mat in a cosy Filipino '
                               'living room, singing happily; Ate holds an open storybook; a bahay kubo picture on '
                               'the wall.',
                     'scene': True}},
            {'id': 'veg',
             'type': 'cards',
             'pose': 'showing.png',
             'goal': 1,
             'title': 'Vegetables in the Garden',
             'say': 'Let us meet some vegetables! (pause) Tap each one. (pause) Say its name with me.',
             'yourTurn': 'Tap each vegetable!',
             'items': [{'word': 'pechay',
                        'sub': 'a leafy vegetable',
                        'img': 'media/image37.png',
                        'say': 'Pechay. (pause) It has big green leaves!'},
                       {'word': 'bawang',
                        'sub': 'garlic',
                        'img': 'media/image41.png',
                        'say': 'Bawang. (pause) In English, garlic. (pause) It is white!'},
                       {'word': 'luya',
                        'sub': 'ginger',
                        'img': 'media/image42.png',
                        'say': 'Luya. (pause) In English, ginger. (pause) It is brown and bumpy!'}],
             'bridge': 'First, let us visit a garden full of vegetables.'},
            {'id': 'song',
             'type': 'chant',
             'pose': 'clapping.png',
             'goal': 1,
             'title': 'Let Us Sing: Bahay Kubo',
             'img': 'media/image44.jpg',
             'say': 'Look at this little house. (pause) It is a bahay kubo. (pause) It has a big garden! (pause) Let '
                    'us sing about it. (pause) Tap a line, or tap the big button to sing it all.',
             'yourTurn': 'Tap a line and sing!',
             'allLabel': 'Sing it all!',
             'lines': [{'text': 'Bahay kubo, kahit munti,'},
                       {'text': 'ang halaman doon ay sari-sari.'},
                       {'text': 'Singkamas at talong, sigarilyas at mani,'},
                       {'text': 'sibuyas, kamatis, bawang at luya!'}],
             'bridge': 'Bawang and luya are in a famous song!'},
            {'id': 'find-veg',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 1,
             'title': 'Find the Vegetable!',
             'say': 'Can you find the vegetables? (pause) Listen. (pause) Then tap!',
             'yourTurn': 'Tap the vegetable!',
             'rounds': [{'ask': 'Tap the garlic!',
                         'askSay': 'Where is the garlic? The bawang?',
                         'choices': [{'word': 'pechay', 'img': 'media/image37.png'},
                                     {'word': 'bawang', 'img': 'media/image41.png', 'ok': True},
                                     {'word': 'luya', 'img': 'media/image42.png'}]},
                        {'ask': 'Tap the ginger!',
                         'askSay': 'Where is the ginger? The luya?',
                         'choices': [{'word': 'luya', 'img': 'media/image42.png', 'ok': True},
                                     {'word': 'bawang', 'img': 'media/image41.png'},
                                     {'word': 'pechay', 'img': 'media/image37.png'}]},
                        {'ask': 'Tap the pechay!',
                         'askSay': 'Where is the pechay? The one with green leaves?',
                         'choices': [{'word': 'bawang', 'img': 'media/image41.png'},
                                     {'word': 'luya', 'img': 'media/image42.png'},
                                     {'word': 'pechay', 'img': 'media/image37.png', 'ok': True}]}],
             'bridge': 'What a lovely song! Now, can you find the vegetables?'},
            {'id': 'move',
             'type': 'act',
             'pose': 'clapping.png',
             'goal': 2,
             'title': 'Sing and Move!',
             'say': 'Please stand up! (pause) Let us sing and move. (pause) Touch each part of your body with me!',
             'yourTurn': 'Touch it, then tap!',
             'cmds': [{'word': 'Touch your feet!',
                       'sub': 'paa',
                       'img': '../../DAY4/INTERACTIVE/media/body-feet.jpg',
                       'art': {'file': '../../DAY4/INTERACTIVE/media/art/body-feet.png',
                               'prompt': 'Tala (Filipino girl, 6) standing and pointing down to her two FEET in '
                                         'white sneakers. That body part is gently highlighted with a soft yellow '
                                         'glow. Full body, front view.'},
                       'say': 'Paa! (pause) Touch your feet!'},
                      {'word': 'Touch your knees!',
                       'sub': 'tuhod',
                       'img': '../../DAY4/INTERACTIVE/media/body-knees.jpg',
                       'art': {'file': '../../DAY4/INTERACTIVE/media/art/body-knees.png',
                               'prompt': 'Tala (Filipino girl, 6) bending forward and touching both KNEES with her '
                                         'hands. That body part is gently highlighted with a soft yellow glow. Full '
                                         'body, front view.'},
                       'say': 'Tuhod! (pause) Touch your knees!'},
                      {'word': 'Touch your shoulders!',
                       'sub': 'balikat',
                       'img': '../../DAY4/INTERACTIVE/media/body-shoulders.jpg',
                       'art': {'file': '../../DAY4/INTERACTIVE/media/art/body-shoulders.png',
                               'prompt': 'Tala (Filipino girl, 6) touching both SHOULDERS with her hands, arms '
                                         'crossed. That body part is gently highlighted with a soft yellow glow. '
                                         'Full body, front view.'},
                       'say': 'Balikat! (pause) Touch your shoulders!'},
                      {'word': 'Touch your head!',
                       'sub': 'ulo',
                       'img': '../../DAY4/INTERACTIVE/media/body-head.jpg',
                       'art': {'file': '../../DAY4/INTERACTIVE/media/art/body-head.png',
                               'prompt': 'Tala (Filipino girl, 6) touching the top of her HEAD with both hands. That '
                                         'body part is gently highlighted with a soft yellow glow. Full body, front '
                                         'view.'},
                       'say': 'Ulo! (pause) Touch your head!'}],
             'bridge': 'Great finding! Now let us sing with our whole body.'},
            {'id': 't1',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': 'The Turtle and the Monkey',
             'page': 'Page 1',
             'art': {'file': 'media/art/turtle-monkey-split.png',
                     'prompt': 'A friendly green turtle and a cheeky brown monkey in a sunny Filipino garden, '
                               'holding a young banana plant cut into two parts: the monkey proudly holds the leafy '
                               'top, the turtle holds the bottom part with roots.',
                     'scene': True},
             'lines': ['Turtle and Monkey find a banana plant.',
                       'They cut it in two.',
                       'Monkey takes the top. Turtle takes the bottom.'],
             'say': 'Story time! (pause) This is Turtle. (pause) And this is Monkey. (pause) One day, they find a '
                    'banana plant. (pause) They cut it in two. (pause) Monkey takes the top. (pause) Turtle takes '
                    'the bottom, with the roots.',
             'bridge': 'You sang and moved! Now sit down. It is story time.'},
            {'id': 't2',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': 'The Turtle and the Monkey',
             'page': 'Page 2',
             'lines': ['Monkey laughs at Turtle.', 'Turtle plants her part.', 'She waters it every day.'],
             'say': 'Monkey laughs at Turtle. (pause) Ha ha! My part has big leaves! (pause) But Turtle plants her '
                    'part in the ground. (pause) She waters it every day.',
             'art': {'file': 'media/art/turtle-planting.png',
                     'prompt': 'The green turtle patiently watering a small banana plant with a little watering can '
                               'in a garden; the monkey in the background laughing and pointing.',
                     'scene': True},
             'bridge': 'Monkey has the leaves. Turtle has the roots. What happens next?'},
            {'id': 't-mid',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 3,
             'title': 'Quick! Who Planted It?',
             'say': 'Quick question!',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'Who planted and watered?',
                         'askSay': 'Who planted the banana plant and watered it every day?',
                         'choices': [{'word': 'Turtle',
                                      'art': {'file': 'media/art/turtle-card.png',
                                              'prompt': 'A friendly green turtle with a kind smile, standing '
                                                        'upright, full body.'},
                                      'ok': True},
                                     {'word': 'Monkey',
                                      'art': {'file': 'media/art/monkey-card.png',
                                              'prompt': 'A cheeky brown monkey with a big grin, standing, full '
                                                        'body.'}}],
                         'yes': 'Yes! Turtle did.',
                         'yesSay': 'Yes! Turtle planted it and watered it. (pause) Let us see what happens!'}],
             'bridge': 'Turtle works hard every day.'},
            {'id': 't3',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': 'The Turtle and the Monkey',
             'lines': ["Monkey's part has no roots.", 'It dries up.', 'It does not grow.'],
             'say': 'Monkey hangs his part on a tree. (pause) But it has no roots. (pause) It dries up. (pause) It '
                    'does not grow at all.',
             'art': {'file': 'media/art/monkey-dry-plant.png',
                     'prompt': 'The monkey looking sad and surprised at his dry, brown, drooping banana leaves '
                               'hanging on a tree branch.',
                     'scene': True},
             'page': 'Page 3',
             'bridge': "Now let us see Monkey's part."},
            {'id': 't4',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': 'The Turtle and the Monkey',
             'img': 'media/image13.jpg',
             'lines': ["Turtle's plant grows tall.", 'It grows bananas!', 'Turtle is kind and patient.'],
             'say': "But Turtle's plant grows tall. (pause) It grows yellow bananas! (pause) Turtle is kind. (pause) "
                    'Turtle is patient. (pause) That is why she has bananas.',
             'page': 'Page 4',
             'bridge': "And what about Turtle's part?"},
            {'id': 't-check',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 3,
             'title': 'Think About the Story',
             'say': 'Let us think about the story.',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'Who was patient?',
                         'askSay': 'Who was kind and patient?',
                         'choices': [{'word': 'Turtle',
                                      'ok': True,
                                      'art': {'file': 'media/art/turtle-card.png',
                                              'prompt': 'A friendly green turtle with a kind smile, standing '
                                                        'upright, full body.'}},
                                     {'word': 'Monkey',
                                      'art': {'file': 'media/art/monkey-card.png',
                                              'prompt': 'A cheeky brown monkey with a big grin, standing, full '
                                                        'body.'}}],
                         'yes': 'Yes! Turtle was patient.',
                         'yesSay': 'Yes! Turtle was kind and patient. (pause) And she got bananas!'}],
             'bridge': 'That is the end of the story. Let us think about it.'},
            {'id': 'p1',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': 'The Legend of the Pineapple',
             'page': 'Page 1',
             'art': {'file': 'media/art/pina-intro.png',
                     'prompt': 'Outside a nipa hut: little girl Pina (7, long black hair, simple dress) sitting and '
                               'playing with a doll while her mother sweeps the yard alone.',
                     'scene': True},
             'lines': ['This is Pina.', 'Pina does not like to help.'],
             'say': 'Here is another story. (pause) The Legend of the Pineapple. (pause) Long ago, there was a girl '
                    'named Pina. (pause) Pina did not like to help her mother.',
             'bridge': 'Turtle was kind and patient. Now, here is a girl who was not helpful.'},
            {'id': 'p2a',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': 'The Legend of the Pineapple',
             'lines': ['Mother is sick.', '"Please cook for us, Pina."', '"I cannot find the pot!"'],
             'say': 'One day, her mother is sick. (pause) Please cook for us, Pina, she says. (pause) But Pina says, '
                    'I cannot find the pot! (pause) I cannot find the spoon! (pause) She does not even look.',
             'art': {'file': 'media/art/pina-kitchen.png',
                     'prompt': 'Inside a cosy nipa-hut kitchen: Pina pouting with arms crossed, not looking around; '
                               'her tired, sick mother resting on a bamboo bed. A clay pot and a wooden spoon are '
                               'clearly visible on the shelf right behind Pina.',
                     'scene': True},
             'page': 'Page 2',
             'bridge': 'Let us see what Pina does at home.'},
            {'id': 'p-mid',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 3,
             'title': 'Quick! Did Pina Look?',
             'say': 'Quick question!',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'Did Pina look for the pot?',
                         'askSay': 'Did Pina really look for the pot?',
                         'choices': [{'word': 'No',
                                      'art': {'file': 'media/art/pina-not-looking.png',
                                              'prompt': 'Pina sitting with arms crossed and eyes closed, not looking '
                                                        'around.'},
                                      'ok': True},
                                     {'word': 'Yes',
                                      'art': {'file': 'media/art/pina-searching.png',
                                              'prompt': 'Pina searching a kitchen shelf, looking carefully with big '
                                                        'curious eyes.'}}],
                         'yes': 'Right! She did not look.',
                         'yesSay': 'Right! Pina did not look. (pause) The pot was right there!'}],
             'bridge': 'Hmm. The pot was right behind her!'},
            {'id': 'p3',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': 'The Legend of the Pineapple',
             'lines': ['Mother is very tired.', '"I wish you had many eyes,"', '"so you can find things!"'],
             'say': 'Her mother is very tired. (pause) She says, I wish you had many eyes, (pause) so you can find '
                    'things!',
             'art': {'file': 'media/art/pina-wish.png',
                     'prompt': 'The tired mother sitting up on the bamboo bed, gently raising one hand as she '
                               'speaks; Pina still pouting by the door. Soft evening light.',
                     'scene': True},
             'page': 'Page 3',
             'bridge': 'Mother is sad and tired.'},
            {'id': 'p4',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': 'The Legend of the Pineapple',
             'page': 'Page 4',
             'art': {'file': 'media/art/pineapple-garden.png',
                     'prompt': 'A small garden beside the doorway of a nipa hut, one big golden pineapple plant '
                               'growing there, the pineapple covered in many little eyes, with a soft magical '
                               'sparkle around it. Gentle and not scary.',
                     'scene': True},
             'lines': ['The next day, Pina is gone.', 'A new fruit grows.', 'It has many, many eyes!'],
             'say': 'The next day, Pina is gone. (pause) In the garden, a new plant grows. (pause) Its fruit has '
                    'many, many eyes! (pause) It is the pineapple. (pause) The pinya!',
             'bridge': 'What happens to Pina?'},
            {'id': 'p-check',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 3,
             'title': 'What Does the Story Teach?',
             'say': 'What does the story teach us?',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'What should we do at home?',
                         'askSay': 'What should we do at home?',
                         'choices': [{'word': 'Help!',
                                      'ok': True,
                                      'art': {'file': 'media/art/help-at-home.png',
                                              'prompt': 'Tala (6) happily helping at home: carrying her plate to the '
                                                        'sink.'}},
                                     {'word': 'Do not help.',
                                      'art': {'file': 'media/art/pina-not-looking.png',
                                              'prompt': 'Pina sitting with arms crossed and eyes closed, not looking '
                                                        'around.'}}],
                         'yes': 'Yes! We help at home.',
                         'yesSay': 'Yes! We help at home. (pause) Every little help is a big help!'}],
             'bridge': 'Two stories, two lessons. Let us think!'},
            {'id': 'verse',
             'type': 'verse',
             'pose': 'praying.png',
             'verse': 'Honor your father and your mother.',
             'ref': 'Exodus 20:12',
             'meaning': 'Be kind like Turtle. Help at home, not like Pina.',
             'say': 'Our Bible verse is, (pause) Honor your father and your mother. (pause) We honor them when we '
                    'help at home.',
             'verseSay': 'Honor your father and your mother. (pause) Exodus twenty, verse twelve.',
             'art': {'file': 'media/art/verse-help.png',
                     'prompt': 'Tala and Bunso helping Nanay set the table for dinner, Tatay smiling, a warm '
                               'Filipino home.',
                     'scene': True},
             'bridge': 'Turtle was kind. We help at home. The Bible tells us why.'},
            {'id': 'done',
             'type': 'celebrate',
             'pose': 'clapping.png',
             'title': 'Great Singing and Listening!',
             'recap': ['I sang Bahay Kubo.', 'I sang and moved my body.', 'Be kind. Help at home.'],
             'say': 'Hooray! (pause) You sang Bahay Kubo. (pause) You moved your body. (pause) And you listened to '
                    'two stories. (pause) See you tomorrow!',
             'bridge': 'You sang, you moved, and you listened!'}]}
