"""Grade 1 English · Q1 W1 D2 · Getting Ready for School.

Source: LANG1Q1W1DAY2NARRATIONSCRIPT (DepEd lesson, Exodus 20:12).
Objectives follow the source: morning-routine words, a story told in order
(first / next / last), and talking about the child's own morning.
"""

LESSON = {'grade': 1,
 'quarter': 1,
 'week': 1,
 'day': 2,
 'title': 'Getting Ready for School',
 'source': 'LANG1Q1W1DAY2NARRATIONSCRIPT — Preparing for School (Exodus 20:12)',
 'bg': 'media/image1.jpg',
 'next': '../../DAY3/INTERACTIVE/index.html',
 'slides': [{'type': 'cover',
             'pose': 'waving.png',
             'goal': 1,
             'title': 'Getting Ready for School',
             'goals': ['Say 5 morning words', 'Tell a story in order', 'Talk about MY morning'],
             'say': 'Good morning, my friend! (pause) I am Tala. (pause) Yesterday we talked about you and your '
                    'family. (pause) Today, we get ready for school!',
             'art': {'file': 'media/art/cover.png',
                     'prompt': 'Tala (6) and her little brother Bunso (5) in Filipino public-school uniforms with '
                               'school bags, waving at the front door of their home on a sunny morning.',
                     'scene': True}},
            {'id': 'words',
             'type': 'cards',
             'pose': 'pointing.png',
             'goal': 1,
             'title': '5 Morning Words',
             'say': 'Every morning, we do five things. (pause) Listen. (pause) Then tap each picture and say the '
                    'words with me!',
             'yourTurn': 'Your turn! Tap each picture!',
             'items': [{'art': {'file': 'media/art/wake-up.png',
                                'prompt': 'Tala (Filipino girl, 6) sitting up in her bed, stretching both arms high '
                                          'and yawning, morning sunlight on her face.'},
                        'word': 'wake up',
                        'img': 'media/image1.jpg',
                        'say': 'Wake up. (pause) We open our eyes.'},
                       {'word': 'take a bath',
                        'img': 'media/image4.jpg',
                        'say': 'Take a bath. (pause) We use soap and water.'},
                       {'art': {'file': 'media/art/get-dressed.png',
                                'prompt': 'Tala (Filipino girl, 6) putting on her Filipino public-school uniform: '
                                          'buttoning a white blouse, blue skirt, school bag beside her.'},
                        'word': 'get dressed',
                        'img': 'media/image5.jpg',
                        'say': 'Get dressed. (pause) We put on our clothes.'},
                       {'word': 'eat breakfast',
                        'img': 'media/image7.jpg',
                        'say': 'Eat breakfast. (pause) Our first food of the day.'},
                       {'word': 'brush teeth',
                        'img': 'media/image8.jpg',
                        'say': 'Brush your teeth. (pause) Clean and shiny!'}],
             'bridge': 'First, let us learn our morning words.'},
            {'id': 'act',
             'type': 'act',
             'pose': 'clapping.png',
             'goal': 1,
             'title': 'Show Me! Act It Out!',
             'say': 'Let us play! (pause) Stand up. (pause) I say the words. (pause) You act them out!',
             'yourTurn': 'Act it out, then tap!',
             'cmds': [{'word': 'Wake up!',
                       'sub': 'Stretch your arms.',
                       'img': 'media/image1.jpg',
                       'say': 'Wake up! (pause) Stretch your arms up high!',
                       'art': {'file': 'media/art/wake-up.png',
                               'prompt': 'Tala (Filipino girl, 6) sitting up in her bed, stretching both arms high '
                                         'and yawning, morning sunlight on her face.'}},
                      {'word': 'Take a bath!',
                       'sub': 'Scrub, scrub, scrub.',
                       'img': 'media/image4.jpg',
                       'say': 'Take a bath! (pause) Scrub, scrub, scrub!'},
                      {'word': 'Get dressed!',
                       'sub': 'Button your shirt.',
                       'img': 'media/image5.jpg',
                       'say': 'Get dressed! (pause) Button your shirt.',
                       'art': {'file': 'media/art/get-dressed.png',
                               'prompt': 'Tala (Filipino girl, 6) putting on her Filipino public-school uniform: '
                                         'buttoning a white blouse, blue skirt, school bag beside her.'}},
                      {'word': 'Eat breakfast!',
                       'sub': 'Yum, yum!',
                       'img': 'media/image7.jpg',
                       'say': 'Eat breakfast! (pause) Yum, yum!'},
                      {'word': 'Brush your teeth!',
                       'sub': 'Up and down.',
                       'img': 'media/image8.jpg',
                       'say': 'Brush your teeth! (pause) Up and down, up and down.'}],
             'bridge': 'You know the five words! Now let us move our bodies.'},
            {'id': 'find',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 1,
             'title': 'Listen and Tap!',
             'say': 'Now, listen carefully. (pause) I say a word. (pause) You tap the right picture.',
             'yourTurn': 'Tap the right picture!',
             'rounds': [{'ask': 'Tap: brush teeth',
                         'askSay': 'Where is brush teeth? Tap it!',
                         'choices': [{'word': 'wake up',
                                      'img': 'media/image1.jpg',
                                      'art': {'file': 'media/art/wake-up.png',
                                              'prompt': 'Tala (Filipino girl, 6) sitting up in her bed, stretching '
                                                        'both arms high and yawning, morning sunlight on her face.'}},
                                     {'word': 'brush teeth', 'img': 'media/image8.jpg', 'ok': True},
                                     {'word': 'get dressed',
                                      'img': 'media/image5.jpg',
                                      'art': {'file': 'media/art/get-dressed.png',
                                              'prompt': 'Tala (Filipino girl, 6) putting on her Filipino '
                                                        'public-school uniform: buttoning a white blouse, blue '
                                                        'skirt, school bag beside her.'}}]},
                        {'ask': 'Tap: eat breakfast',
                         'askSay': 'Where is eat breakfast? Tap it!',
                         'choices': [{'word': 'eat breakfast', 'img': 'media/image7.jpg', 'ok': True},
                                     {'word': 'take a bath', 'img': 'media/image4.jpg'},
                                     {'word': 'brush teeth', 'img': 'media/image8.jpg'}]},
                        {'ask': 'Tap: take a bath',
                         'askSay': 'Where is take a bath? Tap it!',
                         'choices': [{'word': 'get dressed',
                                      'img': 'media/image5.jpg',
                                      'art': {'file': 'media/art/get-dressed.png',
                                              'prompt': 'Tala (Filipino girl, 6) putting on her Filipino '
                                                        'public-school uniform: buttoning a white blouse, blue '
                                                        'skirt, school bag beside her.'}},
                                     {'word': 'wake up',
                                      'img': 'media/image1.jpg',
                                      'art': {'file': 'media/art/wake-up.png',
                                              'prompt': 'Tala (Filipino girl, 6) sitting up in her bed, stretching '
                                                        'both arms high and yawning, morning sunlight on her face.'}},
                                     {'word': 'take a bath', 'img': 'media/image4.jpg', 'ok': True}]}],
             'bridge': 'Great acting! Now let us use our ears.'},
            {'id': 'story1',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': 'Story: Before Going to School',
             'page': 'Page 1',
             'img': 'media/image5.jpg',
             'art': {'file': 'media/art/story-wake-up.png',
                     'prompt': 'Sunrise in a Filipino family bedroom with two beds: Tala (6) and her little brother '
                               'Bunso (5) waking up and stretching, a rooster crowing on the window sill outside.',
                     'scene': True},
             'lines': ['This is Tala and Bunso.', 'They wake up early.', 'It is time for school!'],
             'say': 'Story time! (pause) Our story is called, Before Going to School. (pause) This is Tala and '
                    'Bunso. (pause) They wake up early. (pause) It is time for school!',
             'bridge': 'You know the morning words. Now let us see them in a story!'},
            {'id': 'story2',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': 'Story: Before Going to School',
             'page': 'Page 2',
             'lines': ['They take a bath.', 'They get dressed.', 'They eat breakfast.'],
             'say': 'Nanay says, hurry up! (pause) They take a bath. (pause) They get dressed. (pause) They eat '
                    'breakfast. (pause) Then they brush their teeth.',
             'art': {'file': 'media/art/story-getting-ready.png',
                     'prompt': 'Inside a Filipino home in the morning: Tala and Bunso, hair still wet from the bath, '
                               'sitting at the breakfast table in school uniforms; Nanay serving pandesal and rice; '
                               'a clock on the wall.',
                     'scene': True},
             'bridge': 'What do Tala and Bunso do next?'},
            {'id': 'mid',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 2,
             'title': 'Quick! What Did They Do?',
             'say': 'Quick question!',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'After the bath, they...',
                         'askSay': 'After the bath, what did they do?',
                         'choices': [{'word': 'went to sleep',
                                      'art': {'file': 'media/art/go-to-sleep.png',
                                              'prompt': 'Bunso (Filipino boy, 5) asleep in his bed at night, moon '
                                                        'and stars outside the window.'}},
                                     {'word': 'got dressed',
                                      'img': 'media/image5.jpg',
                                      'ok': True,
                                      'art': {'file': 'media/art/get-dressed.png',
                                              'prompt': 'Tala (Filipino girl, 6) putting on her Filipino '
                                                        'public-school uniform: buttoning a white blouse, blue '
                                                        'skirt, school bag beside her.'}}],
                         'yes': 'Yes! They got dressed.',
                         'yesSay': 'Yes! They got dressed for school. (pause) Let us see what happens next!'}],
             'bridge': 'They did so many things!'},
            {'id': 'story3',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': 'Story: Before Going to School',
             'page': 'Page 3',
             'lines': ['Oh no!', "Bunso's pencil is missing!", "Tala's crayons are missing!"],
             'say': "But wait. (pause) Oh no! (pause) Bunso's pencil is missing! (pause) Tala's crayons are missing! "
                    '(pause) Where can they be?',
             'art': {'file': 'media/art/story-missing.png',
                     'prompt': 'Tala and Bunso kneeling by their open school bags in their bedroom, looking worried: '
                               'Bunso shows an empty pencil case, Tala looks for her crayons.',
                     'scene': True},
             'bridge': 'They are almost ready for school.'},
            {'id': 'feel',
             'type': 'pick',
             'pose': 'sad.png',
             'goal': 2,
             'title': 'How Do They Feel?',
             'say': 'Their things are missing. (pause) How do Tala and Bunso feel?',
             'yourTurn': 'Tap the feeling!',
             'rounds': [{'ask': 'They feel...',
                         'askSay': 'How do Tala and Bunso feel now?',
                         'choices': [{'word': 'worried', 'pose': 'TALA/sad.png', 'ok': True},
                                     {'word': 'happy', 'pose': 'TALA/laughing.png'}],
                         'yes': 'Yes! They feel worried.',
                         'yesSay': 'Yes! They feel worried. (pause) Have you ever lost something?'}],
             'bridge': 'Oh no! Let us stop and think.'},
            {'id': 'story4',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': 'Story: Before Going to School',
             'page': 'Page 4',
             'lines': ['Tatay says, "Hurry up!"',
                       'Nanay says, "I will help you look."',
                       'They look here. They look there.'],
             'say': 'Tatay calls, hurry up, or you will be late! (pause) Nanay says, I will help you look. (pause) '
                    'They look here. (pause) They look there.',
             'art': {'file': 'media/art/story-looking.png',
                     'prompt': 'Nanay (with glasses, yellow sweater) kindly helping Tala and Bunso search their '
                               'bedroom: lifting a pillow, opening a drawer, peeking behind a chair. Tatay at the '
                               'door pointing at his watch.',
                     'scene': True},
             'bridge': 'Who will help them?'},
            {'id': 'story5',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': 'Story: Before Going to School',
             'page': 'Page 5',
             'lines': ['Look! Under the bed!', 'The pencil and the crayons!', '"Thank you, Nanay!"'],
             'say': 'And then. (pause) Look! (pause) Under the bed! (pause) There is the pencil. (pause) And there '
                    'are the crayons! (pause) Thank you, Nanay!',
             'art': {'file': 'media/art/story-found.png',
                     'prompt': 'Bunso lying on the floor reaching under the bed and happily pulling out a pencil and '
                               'a box of crayons; Tala clapping; Nanay smiling beside them.',
                     'scene': True},
             'bridge': 'Will they find the pencil and crayons?'},
            {'id': 'story6',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': 'Story: Before Going to School',
             'page': 'Page 6',
             'lines': ['Nanay says,', '"Put your things away before you sleep."'],
             'say': 'Nanay smiles. (pause) Next time, she says, (pause) put your things away before you sleep. '
                    '(pause) Tala and Bunso say, yes, Nanay!',
             'art': {'file': 'media/art/story-put-away.png',
                     'prompt': 'Evening in the bedroom: Tala putting her crayons into her school bag and Bunso '
                               'zipping his pencil case, Nanay watching with a proud smile.',
                     'scene': True},
             'bridge': 'Now everyone is happy.'},
            {'id': 'order',
             'type': 'order',
             'pose': 'thinking.png',
             'goal': 2,
             'title': 'What Happened First?',
             'say': 'What happened in the story? (pause) Tap the pictures in order. (pause) First. (pause) Next. '
                    '(pause) Last.',
             'yourTurn': 'Tap what happened first!',
             'slots': ['First', 'Next', 'Last'],
             'items': [{'word': 'They got ready.',
                        'say': 'First, they got ready for school.',
                        'art': {'file': 'media/art/story-getting-ready.png',
                                'prompt': 'Inside a Filipino home in the morning: Tala and Bunso, hair still wet '
                                          'from the bath, sitting at the breakfast table in school uniforms; Nanay '
                                          'serving pandesal and rice; a clock on the wall.',
                                'scene': True}},
                       {'word': 'Things were missing.',
                        'say': 'Next, the pencil and crayons were missing.',
                        'art': {'file': 'media/art/story-missing.png',
                                'prompt': 'Tala and Bunso kneeling by their open school bags in their bedroom, '
                                          'looking worried: Bunso shows an empty pencil case, Tala looks for her '
                                          'crayons.',
                                'scene': True}},
                       {'word': 'They found them!',
                        'say': 'Last, they found them under the bed!',
                        'art': {'file': 'media/art/story-found.png',
                                'prompt': 'Bunso lying on the floor reaching under the bed and happily pulling out a '
                                          'pencil and a box of crayons; Tala clapping; Nanay smiling beside them.',
                                'scene': True}}],
             'ask': ['What happened first?', 'What happened next?', 'What happened last?'],
             'yes': 'First, next, last. You did it!',
             'yesSay': 'First, next, last! (pause) You told the whole story!',
             'bridge': 'That is the whole story! Can you remember it?'},
            {'id': 'who',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 2,
             'title': 'Think About the Story',
             'say': 'Let us think about the story.',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'Who helped them look?',
                         'askSay': 'Who helped Tala and Bunso look for their things?',
                         'choices': [{'word': 'Nanay', 'pose': 'NANAY/waving.png', 'ok': True},
                                     {'word': 'Kuya', 'pose': 'KUYA/waving.png'},
                                     {'word': 'Ate', 'pose': 'ATE/waving.png'}],
                         'yes': 'Yes! Nanay helped them.',
                         'yesSay': 'Yes! Nanay helped them. (pause) Our family helps us.'},
                        {'ask': 'Where were the things?',
                         'askSay': 'Where were the pencil and crayons?',
                         'choices': [{'word': 'in the bag',
                                      'art': {'file': 'media/art/in-the-bag.png',
                                              'prompt': 'An open blue school bag with books inside, seen from '
                                                        'above.'}},
                                     {'word': 'under the bed', 'ok': True, 'img': 'media/under-bed.jpg'},
                                     {'word': 'on the table',
                                      'art': {'file': 'media/art/on-the-table.png',
                                              'prompt': 'A small wooden dining table with a plate and a glass of '
                                                        'milk on it.'}}],
                         'yes': 'Yes! Under the bed!',
                         'yesSay': 'Yes! They were under the bed!'}],
             'bridge': 'You remembered the order! Now let us think about the people.'},
            {'id': 'my-morning',
             'type': 'sentence',
             'pose': 'point_self.png',
             'goal': 3,
             'title': 'What do YOU do in the morning?',
             'say': 'Now, let us talk about you! (pause) What do you do in the morning? (pause) Tap one. Then say it '
                    'with me.',
             'yourTurn': 'Tap one and say it!',
             'pre': 'In the morning, I',
             'post': '.',
             'options': [{'word': 'wake up',
                          'img': 'media/image1.jpg',
                          'art': {'file': 'media/art/wake-up.png',
                                  'prompt': 'Tala (Filipino girl, 6) sitting up in her bed, stretching both arms '
                                            'high and yawning, morning sunlight on her face.'}},
                         {'word': 'take a bath', 'img': 'media/image4.jpg'},
                         {'word': 'eat breakfast', 'img': 'media/image7.jpg'},
                         {'word': 'brush my teeth', 'img': 'media/image8.jpg'}],
             'bridge': 'Tala and Bunso got ready for school. What about you?'},
            {'id': 'talk',
             'type': 'talk',
             'pose': 'talking.png',
             'goal': 3,
             'title': 'Your Turn to Talk!',
             'say': 'Tell me about your morning. (pause) Say: First, I wake up. (pause) Next, I eat breakfast. '
                    '(pause) Your turn!',
             'yourTurn': 'Say it out loud!',
             'frame': 'First, I ____. Next, I ____.',
             'example': {'label': 'Tala says', 'text': 'First, I wake up. Next, I eat breakfast.'},
             'art': {'file': 'media/art/talk-my-morning.png',
                     'prompt': 'Tala (6) talking happily, with two picture bubbles beside her: in the first she '
                               'wakes up and stretches, in the second she eats breakfast.'},
             'bridge': 'Now say it all by yourself!'},
            {'id': 'verse',
             'type': 'verse',
             'pose': 'praying.png',
             'verse': 'Honor your father and your mother.',
             'ref': 'Exodus 20:12',
             'meaning': 'Listen to Nanay and Tatay. Say thank you when they help you.',
             'say': 'Our Bible verse is, (pause) Honor your father and your mother. (pause) Honor means we listen to '
                    'them. (pause) And we say thank you, like Tala and Bunso!',
             'verseSay': 'Honor your father and your mother. (pause) Exodus twenty, verse twelve.',
             'art': {'file': 'media/art/verse-family.png',
                     'prompt': 'Tala and Bunso hugging Nanay and Tatay at the front door before school, everyone '
                               'smiling, warm morning light.',
                     'scene': True},
             'bridge': 'Nanay and Tatay helped Tala and Bunso. The Bible tells us how to treat them.'},
            {'id': 'done',
             'type': 'celebrate',
             'pose': 'clapping.png',
             'title': 'You Are Ready for School!',
             'recap': ['I know 5 morning words.', 'I can tell first, next, last.', 'I can talk about my morning.'],
             'say': 'Hooray! (pause) You learned five morning words. (pause) You told the story in order. (pause) '
                    'And you talked about your morning. (pause) See you tomorrow!',
             'bridge': 'You worked so hard today!'}]}
