"""Grade 1 English · Q1 W4 D1 · Things at Home and Polite Words.

Source: Drive SPT/ENG/GRADE1/Q1/WEEK4/DAY1/INTERACTIVE/index.html
("Objects at Home & Polite Requests") + verse slide LANG1-Q1W4-DAY1.png
(Philippians 4:6). No DepEd LANG1Q1W4DAY1 deck/script was found in Drive.
Objectives follow the source: name objects at home (bedroom, school things,
kitchen), make polite requests (please, may I, can you please help me) and
say thank you. The old lesson had no story, so a short story "Bunso Asks
Nicely" carries the polite words from beginning to end.
"""

D1 = "media/art/"

ART = {
    "bed": "One small wooden bed with a colourful Filipino blanket and a white pillow, front view.",
    "pillow": "One soft white pillow with a light-blue edge, fluffy and round.",
    "blanket": "One folded colourful woven Filipino blanket (banig-style stripes) on a plain floor.",
    "book": "One open children's picture book with bright pictures (no readable words) on a plain background.",
    "bag": "One blue children's school backpack with two straps, standing upright.",
    "pencil": "One yellow pencil with a pink eraser, lying diagonally.",
    "plate": "One white round plate with warm rice and a fried egg on it.",
    "spoon": "One shiny metal spoon, lying diagonally.",
    "glass": "One clear glass full of fresh water.",
}


def obj(name, word=None, sub=None, say=None):
    d = {"word": word or name, "art": {"file": D1 + name + ".png", "prompt": ART[name]}}
    if sub:
        d["sub"] = sub
    if say:
        d["say"] = say
    return d


GRAB = {"file": D1 + "story-grab.png",
        "prompt": "Inside a Filipino living room: Bunso (Filipino boy, 5) pulling a picture book out of the hands of "
                  "Tala (Filipino girl, 6). Bunso looks grumpy and demanding, Tala looks sad and surprised.",
        "scene": True}
ASK = {"file": D1 + "story-ask.png",
       "prompt": "Same living room: Bunso (Filipino boy, 5) standing in front of Tala (Filipino girl, 6) with his hands "
                 "pressed together politely, asking gently with a sweet smile; Nanay (glasses, yellow sweater) behind "
                 "them, smiling proudly.",
       "scene": True}
SHARE = {"file": D1 + "story-share.png",
         "prompt": "Same living room: Tala (Filipino girl, 6) happily handing her picture book to Bunso (Filipino boy, "
                   "5), who is smiling and saying thank you; both children happy, Nanay watching with a smile.",
         "scene": True}
THANKS = {"file": D1 + "thank-you-nanay.png",
          "prompt": "Tala (Filipino girl, 6) smiling and saying thank you to Nanay (glasses, yellow sweater), who hands "
                    "her a glass of water in a bright Filipino kitchen. Warm, grateful feeling.",
          "scene": True}

LESSON = {'grade': 1,
 'quarter': 1,
 'week': 4,
 'day': 1,
 'title': 'Things at Home and Polite Words',
 'source': 'Old lesson "Objects at Home & Polite Requests" (Drive WEEK4/DAY1) + LANG1-Q1W4-DAY1.png (Philippians 4:6)',
 'bg': 'media/image3.jpg',
 'next': '../../DAY2/INTERACTIVE/index.html',
 'slides': [{'type': 'cover',
             'pose': 'waving.png',
             'goal': 1,
             'title': 'Things at Home and Polite Words',
             'goals': ['Name things in my home', 'Ask nicely with please', 'Say thank you'],
             'say': 'Hello, my friend! (pause) Last week, we retold the story of the Rooster and the Little Bird. '
                    '(pause) The rooster was kind and shared. (pause) Today, we name things at home. (pause) '
                    'And we learn kind words!',
             'art': {'file': D1 + 'cover-home.png',
                     'prompt': 'Tala (Filipino girl, 6) and her little brother Bunso (Filipino boy, 5) in a cosy '
                               'Filipino home, waving hello. Around them: a bed with a pillow, a school bag, a book '
                               'and a dining table with a plate, a spoon and a glass.',
                     'scene': True}},
            {'id': 'room',
             'type': 'cards',
             'pose': 'pointing.png',
             'goal': 1,
             'title': 'Things in My Bedroom',
             'say': 'This is my bedroom. (pause) Listen to three words. (pause) Tap each picture and say it with me!',
             'yourTurn': 'Tap each picture!',
             'items': [obj('bed', sub='we sleep here', say='Bed. (pause) We sleep on a bed.'),
                       obj('pillow', sub='for my head', say='Pillow. (pause) My head rests on a soft pillow.'),
                       obj('blanket', sub='keeps me warm', say='Blanket. (pause) A blanket keeps me warm.')],
             'bridge': 'First, let us look around my house.'},
            {'id': 'school',
             'type': 'cards',
             'pose': 'holding_book.png',
             'goal': 1,
             'title': 'My School Things',
             'say': 'Here are my school things. (pause) Tap each one. (pause) Say the word!',
             'yourTurn': 'Tap each picture!',
             'items': [obj('book', sub='I read it', say='Book. (pause) I read a book.'),
                       obj('bag', sub='I carry it', say='Bag. (pause) My bag carries my things.'),
                       obj('pencil', sub='I write with it', say='Pencil. (pause) I write with a pencil.')],
             'bridge': 'Bed, pillow, blanket. Now let us find my school things.'},
            {'id': 'kitchen',
             'type': 'cards',
             'pose': 'eating.png',
             'goal': 1,
             'title': 'At the Dining Table',
             'say': 'It is time to eat! (pause) Tap each thing on the table. (pause) Say it with me!',
             'yourTurn': 'Tap each picture!',
             'items': [obj('plate', sub='holds my food', say='Plate. (pause) My rice is on the plate.'),
                       obj('spoon', sub='I eat with it', say='Spoon. (pause) I eat with a spoon.'),
                       obj('glass', sub='holds my water', say='Glass. (pause) A glass of water.')],
             'bridge': 'Book, bag, pencil. Now let us go to the kitchen.'},
            {'id': 'find',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 1,
             'title': 'Listen and Tap!',
             'say': 'Listen carefully. (pause) I say a word. (pause) You tap the picture.',
             'yourTurn': 'Tap the right picture!',
             'rounds': [{'ask': 'Tap: spoon',
                         'askSay': 'Where is the spoon? Tap it!',
                         'choices': [obj('pillow'), obj('spoon') | {'ok': True}, obj('bag')]},
                        {'ask': 'Tap: pillow',
                         'askSay': 'Where is the pillow? Tap it!',
                         'choices': [obj('pencil'), obj('glass'), obj('pillow') | {'ok': True}]},
                        {'ask': 'Tap: book',
                         'askSay': 'Where is the book? Tap it!',
                         'choices': [obj('book') | {'ok': True}, obj('plate'), obj('blanket')]}],
             'bridge': 'You know nine things at home! Let us play a game.'},
            {'id': 'please',
             'type': 'word',
             'pose': 'please.png',
             'goal': 2,
             'word': 'please',
             'wordSay': 'Please.',
             'mean': 'A kind word when we ask',
             'model': 'Please pass the spoon.',
             'say': 'Here is a magic word. (pause) Please! (pause) We say please when we ask for something. '
                    '(pause) Say: Please pass the spoon.',
             'yourTurn': 'Tap the word and say it!',
             'art': {'file': D1 + 'please-word.png',
                     'prompt': 'Tala (Filipino girl, 6) at the dining table with her hands pressed together, '
                               'smiling sweetly and asking Tatay (glasses, navy shirt) to pass the spoon.'},
             'bridge': 'Sometimes we need a spoon, a book or some water. How do we ask?'},
            {'id': 'ask',
             'type': 'chant',
             'pose': 'talking.png',
             'goal': 2,
             'title': 'Kind Ways to Ask',
             'say': 'Here are kind ways to ask. (pause) Tap a line and say it with me. (pause) Use a soft voice!',
             'yourTurn': 'Tap a line and say it!',
             'allLabel': 'Say them all!',
             'lines': [{'text': 'May I please borrow your book?'},
                       {'text': 'Please pass the spoon.'},
                       {'text': 'May I have a glass of water, please?'},
                       {'text': 'Can you please help me carry my bag?'}],
             'art': {'file': D1 + 'kind-ways.png',
                     'prompt': 'Bunso (Filipino boy, 5) politely asking Nanay (glasses, yellow sweater) for a glass '
                               'of water in a bright Filipino kitchen, hands together, Nanay smiling and pouring.'},
             'bridge': 'Please is a magic word. Let us use it with our home words.'},
            {'id': 's1',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': 'Bunso Asks Nicely',
             'page': 'Page 1',
             'lines': ['Tala reads her new book.', 'Bunso sees the book.', 'He wants to read it too!'],
             'say': 'Story time! (pause) Our story is called, Bunso Asks Nicely. (pause) First, Tala reads her new '
                    'book. (pause) Bunso sees it. (pause) He wants to read it too!',
             'art': {'file': D1 + 'story-reading.png',
                     'prompt': 'Tala (Filipino girl, 6) sitting on a mat in a Filipino living room happily reading a '
                               'colourful picture book. Bunso (Filipino boy, 5) peeking at the book with big curious '
                               'eyes.',
                     'scene': True},
             'bridge': 'You can ask nicely. Let us see if Bunso can!'},
            {'id': 's2',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': 'Bunso Asks Nicely',
             'page': 'Page 2',
             'lines': ['Bunso grabs the book.', '"Give me that!" he says.', 'Tala is sad.'],
             'say': 'Next, Bunso grabs the book! (pause) Give me that, he says. (pause) Oh no! (pause) Tala is sad.',
             'art': GRAB,
             'bridge': 'What does Bunso do?'},
            {'id': 'feel',
             'type': 'pick',
             'pose': 'sad.png',
             'goal': 2,
             'title': 'How Does Tala Feel?',
             'say': 'Bunso grabbed the book. (pause) How does Tala feel?',
             'yourTurn': 'Tap the feeling!',
             'rounds': [{'ask': 'Tala feels...',
                         'askSay': 'How does Tala feel now?',
                         'choices': [{'word': 'happy', 'pose': 'TALA/laughing.png'},
                                     {'word': 'sad', 'pose': 'TALA/sad.png', 'ok': True}],
                         'yes': 'Yes! Tala feels sad.',
                         'yesSay': 'Yes! Tala feels sad. (pause) Grabbing is not kind.'}],
             'bridge': 'Oh no! Let us stop and think.'},
            {'id': 's3',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': 'Bunso Asks Nicely',
             'page': 'Page 3',
             'lines': ['Nanay says, "Use the magic word."', 'Bunso gives the book back.',
                       '"May I please borrow your book?"'],
             'say': 'Then Nanay says, Bunso, use the magic word. (pause) Bunso gives the book back. (pause) He asks, '
                    'May I please borrow your book?',
             'art': ASK,
             'bridge': 'Who will help Bunso?'},
            {'id': 's4',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': 'Bunso Asks Nicely',
             'page': 'Page 4',
             'lines': ['Tala smiles. "Yes, you may!"', 'Bunso says, "Thank you, Tala!"', 'Kind words make us happy.'],
             'say': 'Last, Tala smiles. (pause) Yes, you may! (pause) Bunso says, Thank you, Tala! (pause) Kind '
                    'words make everyone happy.',
             'art': SHARE,
             'bridge': 'Bunso asked nicely. What will Tala say?'},
            {'id': 'story-check',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 2,
             'title': 'Think About the Story',
             'say': 'Let us think about the story.',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'Which is the kind way?',
                         'askSay': 'Which is the kind way to ask?',
                         'choices': [{'word': 'Give me that!', 'art': GRAB},
                                     {'word': 'May I please?', 'art': ASK, 'ok': True}],
                         'yes': 'Yes! May I please?',
                         'yesSay': 'Yes! May I please borrow your book? (pause) That is kind.'},
                        {'ask': 'What did Bunso say at the end?',
                         'askSay': 'What did Bunso say at the end?',
                         'choices': [{'word': 'Thank you!', 'art': SHARE, 'ok': True},
                                     {'word': 'Go away!', 'pose': 'BUNSO/sad.png'}],
                         'yes': 'Yes! Thank you!',
                         'yesSay': 'Yes! Bunso said, thank you! (pause) We say thank you when someone shares.'}],
             'bridge': 'That is the end of the story. Let us think.'},
            {'id': 'pass',
             'type': 'sentence',
             'pose': 'giving.png',
             'goal': 2,
             'title': 'Ask at the Table',
             'say': 'Now you ask! (pause) What do you need at the table? (pause) Tap one. Then say it with me.',
             'yourTurn': 'Tap one and say it!',
             'pre': 'Please pass the',
             'post': '.',
             'options': [obj('spoon'), obj('plate'), obj('glass')],
             'bridge': 'Bunso asked for a book. What will you ask for?'},
            {'id': 'talk',
             'type': 'talk',
             'pose': 'talking.png',
             'goal': 3,
             'title': 'Say Thank You!',
             'say': 'When someone helps you, say thank you. (pause) Say: Thank you, Nanay! (pause) Now say it to '
                    'someone at home!',
             'yourTurn': 'Say it out loud!',
             'frame': 'Thank you, ____!',
             'example': {'label': 'Tala says', 'text': 'Thank you, Nanay!'},
             'art': THANKS,
             'bridge': 'Nanay passes the glass. What do you say?'},
            {'id': 'verse',
             'type': 'verse',
             'pose': 'praying.png',
             'verse': 'Present your requests to God with thanksgiving.',
             'ref': 'Philippians 4:6',
             'meaning': 'We can ask God for what we need, and say thank you.',
             'say': 'Our Bible verse is, (pause) Present your requests to God with thanksgiving. (pause) We ask God '
                    'nicely. (pause) And we say thank you to God!',
             'verseSay': 'Present your requests to God (pause) with thanksgiving. (pause) Philippians four, verse '
                         'six.',
             'art': {'file': D1 + 'verse-pray.png',
                     'prompt': 'Tala (6), Bunso (5), Nanay and Tatay sitting at the dining table with plates of rice, '
                               'eyes closed and hands folded, praying and giving thanks before eating.',
                     'scene': True},
             'bridge': 'We ask people nicely. We can ask God too!'},
            {'id': 'done',
             'type': 'celebrate',
             'pose': 'clapping.png',
             'title': 'Kind Words Champion!',
             'recap': ['I can name things in my home.',
                       'I can ask with please and may I.',
                       'I can say thank you.'],
             'say': 'Hooray! (pause) You named things at home. (pause) You asked with please. (pause) And you said '
                    'thank you. (pause) Tomorrow, we look for things that are the same and different!',
             'bridge': 'What a kind day!'}]}
