"""Grade 1 English · Q1 W7 D2 · Writing and Drawing Tools.

Source: no DepEd deck/script found in Drive for LANG1Q1W7. Topic from the old Drive lesson
SPT/ENG/GRADE1/Q1/WEEK7/DAY2/INTERACTIVE/index.html: "Writing and Drawing Tools — Short /e/ &
School Materials" (cards paper, eraser, ruler; value: Pagkamasinop at Pagpapahalaga sa Kagamitan).
The old page was a one-screen stub, so the full lesson is written here. Verse of the week: Luke 16:10.
Objectives: name paper, eraser and ruler; hear and say the short e sound (pen, ten, red, desk);
listen to "Bunso's Ruler" and tell how to use tools the right way.
"""

D1 = '../../DAY1/INTERACTIVE/media/art/'

PENCIL = {'file': D1 + 'pencil.png',
          'prompt': 'One sharp yellow pencil with a pink eraser on the end, lying diagonally.'}
DESK = {'file': D1 + 'desk.png',
        'prompt': 'One small wooden Filipino classroom desk with a matching chair, empty and clean.'}
EGG = {'file': D1 + 'egg.png', 'prompt': 'One white chicken egg, standing upright.'}
PAPER = {'file': 'media/art/paper.png',
         'prompt': 'One clean white sheet of drawing paper, slightly curled at one corner.'}
ERASER = {'file': 'media/art/eraser.png', 'prompt': 'One pink rubber eraser, rectangle shape.'}
RULER = {'file': 'media/art/ruler.png',
         'prompt': 'One straight wooden school ruler with small tick marks and no numbers.'}
PEN = {'file': 'media/art/red-pen.png', 'prompt': 'One red pen with its cap on.'}
BAG = {'file': 'media/art/bag.png', 'prompt': 'One blue Filipino school backpack, zipped shut.'}

LESSON = {'grade': 1,
 'quarter': 1,
 'week': 7,
 'day': 2,
 'title': 'Writing and Drawing Tools',
 'source': 'Old Drive lesson W7 D2 "Writing and Drawing Tools — Short /e/ & School Materials" '
           '(no DepEd deck found); verse Luke 16:10 chosen for the week',
 'bg': 'media/image10.jpg',
 'next': '../../DAY3/INTERACTIVE/index.html',
 'slides': [{'type': 'cover',
             'pose': 'waving.png',
             'goal': 1,
             'title': 'Writing and Drawing Tools',
             'goals': ['Name 3 drawing tools', 'Hear the short e sound', 'Use tools the right way'],
             'say': "Hello again, my friend! (pause) Yesterday, Tala saved her new book. (pause) We named a "
                    'book, a notebook, a desk, and a pencil. (pause) Today, we draw!',
             'art': {'file': 'media/art/cover-drawing.png',
                     'prompt': 'Tala (Filipino girl, 6) and Bunso (her little brother, 5) in school uniforms at '
                               'their classroom desk, ready to draw: white paper, a pink eraser, a wooden ruler '
                               'and a yellow pencil in front of them, both smiling.',
                     'scene': True}},
            {'id': 'words',
             'type': 'cards',
             'pose': 'pointing.png',
             'goal': 1,
             'title': '3 Drawing Tools',
             'say': 'We need three more tools to draw. (pause) Listen. (pause) Then tap each picture and say '
                    'the word!',
             'yourTurn': 'Tap each picture!',
             'items': [{'word': 'paper', 'sub': 'we draw on it', 'art': PAPER,
                        'say': 'Paper. (pause) We write and draw on paper.'},
                       {'word': 'eraser', 'sub': 'it fixes mistakes', 'art': ERASER,
                        'say': 'Eraser. (pause) An eraser fixes our mistakes.'},
                       {'word': 'ruler', 'sub': 'it makes straight lines', 'art': RULER,
                        'say': 'Ruler. (pause) A ruler helps us draw straight lines.'},
                       {'word': 'pencil', 'sub': 'we write with it', 'art': PENCIL,
                        'say': 'And our friend from yesterday, the pencil!'}],
             'bridge': 'Let us get ready to draw.'},
            {'id': 'act',
             'type': 'act',
             'pose': 'clapping.png',
             'goal': 3,
             'title': 'Show Me! Use Your Tools!',
             'say': 'Let us pretend to draw! (pause) I say it. (pause) You act it out!',
             'yourTurn': 'Act it out, then tap!',
             'cmds': [{'word': 'Hold your paper!', 'sub': 'Hold it flat.', 'art': PAPER,
                       'say': 'Hold your paper! (pause) Hold it flat.'},
                      {'word': 'Draw a line!', 'sub': 'Use your ruler.', 'art': RULER,
                       'say': 'Draw a line! (pause) Slide your pencil along the ruler.'},
                      {'word': 'Erase it!', 'sub': 'Rub, rub, gently.', 'art': ERASER,
                       'say': 'Erase it! (pause) Rub, rub, gently.'}],
             'bridge': 'You know the drawing tools! Now let us use them.'},
            {'id': 'find',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 1,
             'title': 'Listen and Tap!',
             'say': 'Listen carefully. (pause) Tap the right picture.',
             'yourTurn': 'Tap the right picture!',
             'rounds': [{'ask': 'Tap: eraser',
                         'askSay': 'Where is the eraser? Tap it!',
                         'choices': [{'word': 'ruler', 'art': RULER},
                                     {'word': 'eraser', 'art': ERASER, 'ok': True},
                                     {'word': 'paper', 'art': PAPER}]},
                        {'ask': 'Tap: ruler',
                         'askSay': 'Where is the ruler? Tap it!',
                         'choices': [{'word': 'ruler', 'art': RULER, 'ok': True},
                                     {'word': 'pencil', 'art': PENCIL},
                                     {'word': 'eraser', 'art': ERASER}]}],
             'bridge': 'Good drawing! Now use your ears.'},
            {'id': 'short-e',
             'type': 'chant',
             'pose': 'clapping.png',
             'goal': 2,
             'title': 'The Short e Song',
             'say': 'Remember, e, e, egg? (pause) Listen for e, e in these words. (pause) Tap a line and say '
                    'it with me!',
             'yourTurn': 'Tap a line and say it!',
             'allLabel': 'Say it all!',
             'lines': [{'text': 'e, e, egg!'},
                       {'text': 'Ten red pens,'},
                       {'text': 'on my desk!'},
                       {'text': 'e, e, e!'}],
             'art': {'file': 'media/art/ten-red-pens.png',
                     'prompt': 'Ten red pens lined up neatly on a small wooden classroom desk, with a white egg '
                               'beside them; Bunso (Filipino boy, 5) counting them with his finger and smiling.',
                     'scene': True},
             'bridge': 'Yesterday we sang a, e, i, o, u. Today we sing the e sound!'},
            {'id': 'e-tap',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 2,
             'title': 'Find the Short e!',
             'say': 'Listen for e, e. (pause) Tap the word with the short e sound!',
             'yourTurn': 'Tap the e word!',
             'rounds': [{'ask': 'Which has e, e?',
                         'askSay': 'Pen. (pause) Bag. (pause) Which one has e, e?',
                         'choices': [{'word': 'pen', 'art': PEN, 'ok': True},
                                     {'word': 'bag', 'art': BAG}],
                         'yes': 'Yes! p, e, n. Pen!',
                         'yesSay': 'Yes! p, e, n. (pause) Pen has the short e!'},
                        {'ask': 'Which has e, e?',
                         'askSay': 'Desk. (pause) Book. (pause) Which one has e, e?',
                         'choices': [{'word': 'book',
                                      'art': {'file': D1 + 'book.png',
                                              'prompt': "One colourful children's storybook lying closed, a "
                                                        'picture of a smiling sun on the cover (no letters).'}},
                                     {'word': 'desk', 'art': DESK, 'ok': True}],
                         'yes': 'Yes! d, e, sk. Desk!',
                         'yesSay': 'Yes! d, e, sk. (pause) Desk has the short e too!'}],
             'bridge': 'Ten red pens! Can you find more e words?'},
            {'id': 's1',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': "Story: Bunso's Ruler",
             'page': 'Page 1',
             'lines': ['It is drawing time.', 'Teacher Ana says,', '"Draw a line with your ruler."'],
             'say': "Story time! (pause) Our story is Bunso's Ruler. (pause) It is drawing time. (pause) "
                    'Teacher Ana says, draw a straight line with your ruler.',
             'art': {'file': 'media/art/story-drawing-time.png',
                     'prompt': 'Filipino Grade 1 classroom at drawing time: Teacher Ana (kind Filipino woman, '
                               '30s, light-blue blouse, hair in a bun) showing how to draw a straight line with a '
                               'ruler; Tala (6) and Bunso (5) at their desks with paper, rulers and pencils.',
                     'scene': True},
             'bridge': 'Now let us read a story about a ruler.'},
            {'id': 's2',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': "Story: Bunso's Ruler",
             'page': 'Page 2',
             'lines': ['Bunso does not draw.', 'He waves his ruler like a sword.', '"Look! I am a hero!"'],
             'say': 'But Bunso does not draw. (pause) He waves his ruler like a sword! (pause) Swish, swish! '
                    '(pause) Look, I am a hero, he says.',
             'art': {'file': 'media/art/story-ruler-sword.png',
                     'prompt': 'Bunso (Filipino boy, 5) standing by his desk playfully waving a wooden ruler '
                               'like a sword, big grin; Tala (6) watching with a worried face.',
                     'scene': True},
             'bridge': 'What does Bunso do with his ruler?'},
            {'id': 'mid',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 3,
             'title': 'Quick! What Is a Ruler For?',
             'say': 'Quick question!',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'A ruler is for...',
                         'askSay': 'What is a ruler for?',
                         'choices': [{'word': 'straight lines',
                                      'ok': True,
                                      'art': {'file': 'media/art/ruler-line.png',
                                              'prompt': 'A child\'s hand drawing a straight pencil line on white '
                                                        'paper along a wooden ruler.'}},
                                     {'word': 'sword play',
                                      'art': {'file': 'media/art/story-ruler-sword.png',
                                              'prompt': 'Bunso (Filipino boy, 5) standing by his desk playfully '
                                                        'waving a wooden ruler like a sword, big grin; Tala (6) '
                                                        'watching with a worried face.',
                                              'scene': True}}],
                         'yes': 'Yes! Straight lines!',
                         'yesSay': 'Yes! A ruler is for straight lines. (pause) Not for sword play!'}],
             'bridge': 'Hmm. Is that the right way to use a ruler?'},
            {'id': 's3',
             'type': 'story',
             'pose': 'sad.png',
             'goal': 3,
             'title': "Story: Bunso's Ruler",
             'page': 'Page 3',
             'lines': ['Swish! Snap!', 'The ruler breaks in two.', 'Now Bunso cannot draw a line.'],
             'say': 'Swish! (pause) Snap! (pause) The ruler hits the desk. (pause) It breaks in two! (pause) Now '
                    'Bunso cannot draw a straight line.',
             'art': {'file': 'media/art/story-ruler-broken.png',
                     'prompt': 'Bunso (Filipino boy, 5) sadly holding two halves of a broken wooden ruler at his '
                               'desk, blank white paper in front of him, tears in his eyes.',
                     'scene': True},
             'bridge': 'Then something happens.'},
            {'id': 'feel',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 3,
             'title': 'How Does Bunso Feel?',
             'say': 'His ruler is broken. (pause) How does Bunso feel?',
             'yourTurn': 'Tap the feeling!',
             'rounds': [{'ask': 'Bunso feels...',
                         'askSay': 'How does Bunso feel now?',
                         'choices': [{'word': 'sad', 'pose': 'BUNSO/sad.png', 'ok': True},
                                     {'word': 'happy', 'pose': 'BUNSO/laughing.png'}],
                         'yes': 'Yes! Bunso is sad.',
                         'yesSay': 'Yes! Bunso is sad. (pause) Who can help him?'}],
             'bridge': 'Oh no! Let us stop and think.'},
            {'id': 's4',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': "Story: Bunso's Ruler",
             'page': 'Page 4',
             'lines': ['Tala says, "Use my ruler, please be careful."', 'Bunso says, "Thank you, Ate!"',
                       '"I am sorry I played."'],
             'say': 'Tala says, you can use my ruler. (pause) Please be careful. (pause) Thank you, Ate! (pause) '
                    'I am sorry I played with my ruler.',
             'art': {'file': 'media/art/story-share-ruler.png',
                     'prompt': 'Tala (Filipino girl, 6) kindly handing her own wooden ruler to Bunso (5) across '
                               'the desk; Bunso taking it with both hands and a grateful smile.',
                     'scene': True},
             'bridge': 'Who helps Bunso?'},
            {'id': 's5',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': "Story: Bunso's Ruler",
             'page': 'Page 5',
             'lines': ['Bunso draws a straight line.', 'He erases a mistake gently.', 'Tools are for working!'],
             'say': 'Bunso draws a straight line. (pause) He erases a mistake, gently. (pause) He uses both '
                    'sides of the paper. (pause) Tools are for working, not for playing!',
             'art': {'file': 'media/art/story-right-way.png',
                     'prompt': 'Bunso (5) carefully drawing a straight line along a ruler and gently erasing a '
                               'small mark with a pink eraser; Tala (6) and Teacher Ana (light-blue blouse) '
                               'smiling proudly behind him.',
                     'scene': True},
             'bridge': 'Now Bunso can draw!'},
            {'id': 'order',
             'type': 'order',
             'pose': 'thinking.png',
             'goal': 3,
             'title': 'What Happened First?',
             'say': 'Let us retell the story. (pause) Tap the pictures in order. (pause) Beginning. (pause) '
                    'Middle. (pause) End.',
             'yourTurn': 'Tap what happened first!',
             'slots': ['Beginning', 'Middle', 'End'],
             'items': [{'word': 'Bunso plays sword.',
                        'say': 'Beginning: Bunso plays with his ruler.',
                        'art': {'file': 'media/art/story-ruler-sword.png',
                                'prompt': 'Bunso (Filipino boy, 5) standing by his desk playfully waving a '
                                          'wooden ruler like a sword, big grin; Tala (6) watching with a '
                                          'worried face.',
                                'scene': True}},
                       {'word': 'The ruler breaks.',
                        'say': 'Middle: the ruler breaks.',
                        'art': {'file': 'media/art/story-ruler-broken.png',
                                'prompt': 'Bunso (Filipino boy, 5) sadly holding two halves of a broken wooden '
                                          'ruler at his desk, blank white paper in front of him, tears in his '
                                          'eyes.',
                                'scene': True}},
                       {'word': 'Bunso draws nicely.',
                        'say': 'End: Bunso uses the ruler the right way.',
                        'art': {'file': 'media/art/story-right-way.png',
                                'prompt': 'Bunso (5) carefully drawing a straight line along a ruler and gently '
                                          'erasing a small mark with a pink eraser; Tala (6) and Teacher Ana '
                                          '(light-blue blouse) smiling proudly behind him.',
                                'scene': True}}],
             'ask': ['What happened at the beginning?', 'What happened in the middle?', 'What happened at the end?'],
             'yes': 'Beginning, middle, end. You did it!',
             'yesSay': 'Beginning, middle, end! (pause) You retold the whole story!',
             'bridge': 'That is the end of the story. Can you retell it?'},
            {'id': 'right-way',
             'type': 'pick',
             'pose': 'pointing.png',
             'goal': 3,
             'title': 'Which Is the Right Way?',
             'say': 'Let us be like Bunso at the end. (pause) Tap the right way to use our tools!',
             'yourTurn': 'Tap the right way!',
             'rounds': [{'ask': 'Which is the right way?',
                         'askSay': 'Look at the eraser. (pause) Which is the right way?',
                         'choices': [{'word': 'erase gently',
                                      'ok': True,
                                      'art': {'file': 'media/art/erase-gently.png',
                                              'prompt': 'A child\'s hand gently rubbing a pink eraser on a small '
                                                        'pencil mark on white paper.'}},
                                     {'word': 'tear the paper',
                                      'art': {'file': 'media/art/tear-paper.png',
                                              'prompt': 'A sheet of white paper torn in half, the two pieces '
                                                        'lying on a desk.'}}],
                         'yes': 'Yes! Erase gently.',
                         'yesSay': 'Yes! We erase gently, so the paper does not tear.'},
                        {'ask': 'Which is the right way?',
                         'askSay': 'Look at the ruler. (pause) Which is the right way?',
                         'choices': [{'word': 'sword play',
                                      'art': {'file': 'media/art/story-ruler-sword.png',
                                              'prompt': 'Bunso (Filipino boy, 5) standing by his desk playfully '
                                                        'waving a wooden ruler like a sword, big grin; Tala (6) '
                                                        'watching with a worried face.',
                                              'scene': True}},
                                     {'word': 'draw a line',
                                      'ok': True,
                                      'art': {'file': 'media/art/ruler-line.png',
                                              'prompt': 'A child\'s hand drawing a straight pencil line on white '
                                                        'paper along a wooden ruler.'}}],
                         'yes': 'Yes! Draw a line.',
                         'yesSay': 'Yes! A ruler helps us draw a straight line.'}],
             'bridge': 'Bunso learned the right way. Do you know it too?'},
            {'id': 'my-tool',
             'type': 'talk',
             'pose': 'talking.png',
             'goal': 3,
             'title': 'Your Turn to Talk!',
             'say': 'Pick one tool. (pause) Tell me how you use it. (pause) Say: I use an eraser to fix my '
                    'mistake. (pause) Your turn!',
             'yourTurn': 'Say it out loud!',
             'frame': 'I use a ____ to ____.',
             'example': {'label': 'Bunso says', 'text': 'I use a ruler to draw a line.'},
             'art': {'file': 'media/art/talk-ruler.png',
                     'prompt': 'Bunso (Filipino boy, 5) proudly holding up his paper with a long straight line '
                               'on it, a ruler in his other hand, happy face.'},
             'bridge': 'Now you tell me how YOU use a tool!'},
            {'id': 'verse',
             'type': 'verse',
             'pose': 'praying.png',
             'verse': 'Whoever can be trusted with very little can also be trusted with much.',
             'ref': 'Luke 16:10',
             'meaning': 'Use your ruler, eraser and paper with care.',
             'say': 'Our Bible verse again! (pause) A ruler is a small thing. (pause) When we use it with care, '
                    'we can be trusted!',
             'verseSay': 'Whoever can be trusted with very little (pause) can also be trusted with much. '
                         '(pause) Luke sixteen, verse ten.',
             'art': {'file': 'media/art/verse-ruler.png',
                     'prompt': 'Tala (6) and Bunso (5) neatly putting rulers, erasers and pencils into one pencil '
                               'case at a tidy classroom desk, Teacher Ana (light-blue blouse) giving a thumbs up, '
                               'warm golden light.',
                     'scene': True},
             'bridge': 'Bunso learned to care for his tools. The Bible says that is important.'},
            {'id': 'done',
             'type': 'celebrate',
             'pose': 'clapping.png',
             'title': 'Great Drawing Today!',
             'recap': ['I know: paper, eraser, ruler.',
                       'I hear e in pen, ten, red, desk.',
                       'I use tools the right way.'],
             'say': 'Hooray! (pause) You named three drawing tools. (pause) You found the short e sound. (pause) '
                    'And you use tools the right way! (pause) Tomorrow, we color with crayons!',
             'bridge': 'You worked so hard today!'}]}
