"""Grade 1 English · Q1 W8 D1 · Meeting Good Friends at School.

Source: old Drive lesson SPT/ENG/GRADE1/Q1/WEEK8/DAY1/INTERACTIVE/index.html
("Meeting Good Friends at School — Polite Words & Friendship"; words friend,
smile, greet; check: greet teacher and friends with "Good morning"). No DepEd
deck/script exists for Week 8 and no verse PNG, so the week uses one short
verse: "A friend loves at all times." (Proverbs 17:17).
Objectives: learn friendship words (friend, smile, greet, wave); listen to
"Tala's New Friend" and tell what happened in order; greet a classmate and
say one's name.
"""

LINO = 'Lino (Filipino boy, 6, the new classmate: curly black hair, green T-shirt, brown shorts, small red school bag)'
ROOM = 'a bright Filipino Grade 1 classroom with a green chalkboard, small wooden desks and paper flowers on the wall'

LESSON = {'grade': 1,
 'quarter': 1,
 'week': 8,
 'day': 1,
 'title': 'Meeting Good Friends at School',
 'source': 'Old Drive lesson Q1 W8 D1 "Meeting Good Friends at School" (no DepEd deck found); verse Proverbs 17:17',
 'bg': 'media/image10.jpg',
 'next': '../../DAY2/INTERACTIVE/index.html',
 'slides': [{'type': 'cover',
             'pose': 'waving.png',
             'goal': 1,
             'title': 'Meeting Good Friends at School',
             'goals': ['Say 4 friendship words', "Listen to Tala's friend story", 'Greet a friend and say my name'],
             'say': 'Good morning, my friend! (pause) Last time, we met our teacher and the chalkboard. '
                    '(pause) Today, we meet new friends at school!',
             'art': {'file': 'media/art/cover-friends.png',
                     'prompt': 'Tala (Filipino girl, 6) and ' + LINO + ' smiling and waving at each other in ' + ROOM
                               + '; the teacher writes at the chalkboard behind them. Warm, happy first-meeting mood.',
                     'scene': True}},
            {'id': 'words',
             'type': 'cards',
             'pose': 'pointing.png',
             'goal': 1,
             'title': '4 Friendship Words',
             'say': 'Here are four friendship words. (pause) Listen. (pause) Then tap each picture and say it with me!',
             'yourTurn': 'Tap each picture!',
             'items': [{'word': 'friend',
                        'sub': 'someone kind we play with',
                        'art': {'file': 'media/art/word-friend.png',
                                'prompt': 'Tala (Filipino girl, 6) and ' + LINO + ' standing side by side, arms '
                                          'around each other, both smiling big.'},
                        'say': 'Friend. (pause) A friend is someone kind we play with.'},
                       {'word': 'smile',
                        'sub': 'a happy face',
                        'pose': 'TALA/laughing.png',
                        'say': 'Smile. (pause) A smile is a happy face. (pause) Show me your smile!'},
                       {'word': 'greet',
                        'sub': 'say Good morning!',
                        'art': {'file': 'media/art/word-greet.png',
                                'prompt': 'Tala (Filipino girl, 6) at the classroom door greeting her smiling '
                                          'teacher with a small bow and a happy open mouth, as if saying good '
                                          'morning.'},
                        'say': 'Greet. (pause) When we greet, we say, Good morning!'},
                       {'word': 'wave',
                        'sub': 'move your hand hello',
                        'pose': 'TALA/waving.png',
                        'say': 'Wave. (pause) We wave our hand to say hello.'}],
             'bridge': 'To make a friend, we need some special words.'},
            {'id': 'act',
             'type': 'act',
             'pose': 'clapping.png',
             'goal': 1,
             'title': 'Show Me! Be a Friend!',
             'say': 'Stand up! (pause) I say it. (pause) You do it. (pause) Then tap the button.',
             'yourTurn': 'Do it, then tap!',
             'cmds': [{'word': 'Smile!', 'sub': 'A big happy face.', 'pose': 'TALA/laughing.png',
                       'say': 'Smile! (pause) Show me a big happy face!'},
                      {'word': 'Wave!', 'sub': 'Hello, hello!', 'pose': 'TALA/waving.png',
                       'say': 'Wave! (pause) Hello, hello!'},
                      {'word': 'Greet!', 'sub': 'Say, Good morning!',
                       'art': {'file': 'media/art/word-greet.png',
                               'prompt': 'Tala (Filipino girl, 6) at the classroom door greeting her smiling '
                                         'teacher with a small bow and a happy open mouth, as if saying good '
                                         'morning.'},
                       'say': 'Greet! (pause) Say, Good morning!'},
                      {'word': 'Say your name!', 'sub': 'My name is...', 'pose': 'TALA/point_self.png',
                       'say': 'Point to yourself. (pause) Say, My name is, and your name!'}],
             'bridge': 'You know the words! Now let us practice being a friend.'},
            {'id': 'find',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 1,
             'title': 'Listen and Tap!',
             'say': 'Listen carefully. (pause) I say a word. (pause) You tap the picture.',
             'yourTurn': 'Tap the right picture!',
             'rounds': [{'ask': 'Tap: smile',
                         'askSay': 'Where is smile? Tap it!',
                         'choices': [{'word': 'wave', 'pose': 'TALA/waving.png'},
                                     {'word': 'smile', 'pose': 'TALA/laughing.png', 'ok': True},
                                     {'word': 'sad', 'pose': 'TALA/sad.png'}]},
                        {'ask': 'Tap: friend',
                         'askSay': 'Where are the friends? Tap them!',
                         'choices': [{'word': 'friend', 'ok': True,
                                      'art': {'file': 'media/art/word-friend.png',
                                              'prompt': 'Tala (Filipino girl, 6) and ' + LINO + ' standing side by '
                                                        'side, arms around each other, both smiling big.'}},
                                     {'word': 'wave', 'pose': 'TALA/waving.png'},
                                     {'word': 'think', 'pose': 'TALA/thinking.png'}]}],
             'bridge': 'Great acting! Now use your ears.'},
            {'id': 's1',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': "Story: Tala's New Friend",
             'page': 'Page 1',
             'lines': ['It is Monday at school.', 'A new boy comes in.', 'His name is Lino.'],
             'say': "Story time! (pause) Our story is, Tala's New Friend. (pause) It is Monday at school. "
                    '(pause) A new boy comes in. (pause) His name is Lino.',
             'art': {'file': 'media/art/story-new-boy.png',
                     'prompt': 'Morning in ' + ROOM + ': ' + LINO + ' stands at the classroom door holding his bag '
                               'strap, looking around. Tala (Filipino girl, 6) and Bunso sit at their desks and '
                               'notice him.',
                     'scene': True},
             'bridge': 'You can greet and smile. Now let us see it in a story!'},
            {'id': 's2',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': "Story: Tala's New Friend",
             'page': 'Page 2',
             'lines': ['Lino sits alone.', 'He looks down.', 'He does not know anyone.'],
             'say': 'Lino sits alone at his desk. (pause) He looks down. (pause) He does not know anyone yet.',
             'art': {'file': 'media/art/story-alone.png',
                     'prompt': LINO + ' sitting alone at a desk at the back of ' + ROOM + ', head down, shy and a '
                               'little sad, while other children chat in small groups.',
                     'scene': True},
             'bridge': 'What does Lino do?'},
            {'id': 'feel',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 2,
             'title': 'How Does Lino Feel?',
             'say': 'Look at Lino. (pause) He is new. (pause) He sits alone.',
             'yourTurn': 'Tap the feeling!',
             'rounds': [{'ask': 'Lino feels...',
                         'askSay': 'How does Lino feel?',
                         'choices': [{'word': 'shy and sad', 'ok': True,
                                      'art': {'file': 'media/art/lino-shy.png',
                                              'prompt': LINO + ', looking shy and a little sad, eyes down, hands '
                                                        'holding his bag strap. Full body.'}},
                                     {'word': 'happy', 'pose': 'TALA/laughing.png'}],
                         'yes': 'Yes! Lino feels shy.',
                         'yesSay': 'Yes! Lino feels shy and a little sad. (pause) Who can help him?'}],
             'bridge': 'Oh no. Let us think about Lino.'},
            {'id': 's3',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': "Story: Tala's New Friend",
             'page': 'Page 3',
             'lines': ['Tala smiles and waves.', '"Good morning! My name is Tala."', '"What is your name?"'],
             'say': 'Tala sees Lino. (pause) She smiles and waves. (pause) Good morning! My name is Tala. '
                    '(pause) What is your name?',
             'art': {'file': 'media/art/story-greet.png',
                     'prompt': 'Tala (Filipino girl, 6) walking up to ' + LINO + ' at his desk, smiling and '
                               'waving hello; Lino looks up, surprised and starting to smile. In ' + ROOM + '.',
                     'scene': True},
             'bridge': 'Then, Tala has an idea.'},
            {'id': 's4',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 2,
             'title': "Story: Tala's New Friend",
             'page': 'Page 4',
             'lines': ['Lino smiles. "My name is Lino."', '"Do you want to draw with us?"', 'Now they are friends!'],
             'say': 'Lino smiles. (pause) Good morning, Tala! My name is Lino. (pause) Tala says, do you want to '
                    'draw with us? (pause) Yes! (pause) Now they are friends!',
             'art': {'file': 'media/art/story-friends-draw.png',
                     'prompt': 'Tala (Filipino girl, 6), Bunso and ' + LINO + ' sitting together at one desk, '
                               'drawing with crayons on paper and laughing. In ' + ROOM + '.',
                     'scene': True},
             'bridge': 'What does Lino say?'},
            {'id': 'check',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 2,
             'title': 'Think About the Story',
             'say': 'Let us think about the story.',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'Who is the new boy?',
                         'askSay': 'Who is the new boy in class?',
                         'choices': [{'word': 'Lino', 'ok': True,
                                      'art': {'file': 'media/art/lino-card.png',
                                              'prompt': LINO + ', standing and smiling, full body, front view.'}},
                                     {'word': 'Bunso', 'pose': 'BUNSO/waving.png'},
                                     {'word': 'Kuya', 'pose': 'KUYA/waving.png'}],
                         'yes': 'Yes! Lino!',
                         'yesSay': 'Yes! Lino is the new boy.'},
                        {'ask': 'What did Tala say?',
                         'askSay': 'What did Tala say to Lino?',
                         'choices': [{'word': 'Good morning!', 'ok': True,
                                      'art': {'file': 'media/art/word-greet.png',
                                              'prompt': 'Tala (Filipino girl, 6) at the classroom door greeting her '
                                                        'smiling teacher with a small bow and a happy open mouth, as '
                                                        'if saying good morning.'}},
                                     {'word': 'Go away!', 'pose': 'TALA/exclaiming.png'}],
                         'yes': 'Yes! Good morning!',
                         'yesSay': 'Yes! Tala said, Good morning! My name is Tala.'}],
             'bridge': 'Tala made a new friend!'},
            {'id': 'order',
             'type': 'order',
             'pose': 'thinking.png',
             'goal': 2,
             'title': 'What Happened First?',
             'say': 'Tap the pictures in order. (pause) First. (pause) Next. (pause) Last.',
             'yourTurn': 'Tap what happened first!',
             'slots': ['First', 'Next', 'Last'],
             'items': [{'word': 'Lino sat alone.',
                        'say': 'First, Lino sat alone.',
                        'art': {'file': 'media/art/story-alone.png',
                                'prompt': LINO + ' sitting alone at a desk at the back of ' + ROOM + ', head down, '
                                          'shy and a little sad, while other children chat in small groups.',
                                'scene': True}},
                       {'word': 'Tala greeted Lino.',
                        'say': 'Next, Tala smiled and greeted Lino.',
                        'art': {'file': 'media/art/story-greet.png',
                                'prompt': 'Tala (Filipino girl, 6) walking up to ' + LINO + ' at his desk, smiling '
                                          'and waving hello; Lino looks up, surprised and starting to smile. In '
                                          + ROOM + '.',
                                'scene': True}},
                       {'word': 'They drew together.',
                        'say': 'Last, they drew together. They are friends!',
                        'art': {'file': 'media/art/story-friends-draw.png',
                                'prompt': 'Tala (Filipino girl, 6), Bunso and ' + LINO + ' sitting together at one '
                                          'desk, drawing with crayons on paper and laughing. In ' + ROOM + '.',
                                'scene': True}}],
             'ask': ['What happened first?', 'What happened next?', 'What happened last?'],
             'yes': 'First, next, last. You did it!',
             'yesSay': 'First, next, last! (pause) You told the whole story!',
             'bridge': 'Can you remember the whole story?'},
            {'id': 'greet-words',
             'type': 'sentence',
             'pose': 'point_self.png',
             'goal': 3,
             'title': 'How Do YOU Greet?',
             'say': 'How do you greet a friend? (pause) Tap one. (pause) Then say it with me.',
             'yourTurn': 'Tap one and say it!',
             'pre': 'I say,',
             'post': '',
             'options': [{'word': 'Good morning!',
                          'art': {'file': 'media/art/greet-morning.png',
                                  'prompt': 'Tala (Filipino girl, 6) waving hello to a friend in the morning '
                                            'sunshine at the school gate.'}},
                         {'word': 'Good afternoon!',
                          'art': {'file': 'media/art/greet-afternoon.png',
                                  'prompt': 'Tala (Filipino girl, 6) waving hello to a friend under an orange '
                                            'afternoon sky at the school playground.'}},
                         {'word': 'Hello, friend!', 'pose': 'TALA/waving.png'}],
             'bridge': 'Tala greeted Lino. How do YOU greet a friend?'},
            {'id': 'talk',
             'type': 'talk',
             'pose': 'talking.png',
             'goal': 3,
             'title': 'Your Turn to Talk!',
             'say': 'Turn to a friend or a family member. (pause) Smile and wave. (pause) Say: Good morning! My '
                    'name is Tala. (pause) Use your own name!',
             'yourTurn': 'Say it out loud!',
             'frame': 'Good morning! My name is ____.',
             'example': {'label': 'Lino says', 'text': 'Good morning! My name is Lino.'},
             'art': {'file': 'media/art/story-greet.png',
                     'prompt': 'Tala (Filipino girl, 6) walking up to ' + LINO + ' at his desk, smiling and '
                               'waving hello; Lino looks up, surprised and starting to smile. In ' + ROOM + '.',
                     'scene': True},
             'bridge': 'Now make a new friend, just like Tala!'},
            {'id': 'verse',
             'type': 'verse',
             'pose': 'praying.png',
             'verse': 'A friend loves at all times.',
             'ref': 'Proverbs 17:17',
             'meaning': 'A good friend is kind every day.',
             'say': 'Our Bible verse this week is, (pause) A friend loves at all times. (pause) That means, a good '
                    'friend is kind every day. (pause) Like Tala!',
             'verseSay': 'A friend loves at all times. (pause) Proverbs seventeen, verse seventeen.',
             'art': {'file': 'media/art/verse-friends.png',
                     'prompt': 'Tala (Filipino girl, 6), ' + LINO + ' and Bunso walking out of the school gate '
                               'together holding hands and smiling, warm afternoon light.',
                     'scene': True},
             'bridge': 'Tala was kind to Lino. The Bible tells us about friends.'},
            {'id': 'done',
             'type': 'celebrate',
             'pose': 'clapping.png',
             'title': 'You Can Make Friends!',
             'recap': ['I know: friend, smile, greet, wave.',
                       "I told Tala's story in order.",
                       'I can greet and say my name.'],
             'say': 'Hooray! (pause) You learned four friendship words. (pause) You told the story in order. '
                    '(pause) And you greeted a friend! (pause) Tomorrow, we learn to share and help!',
             'bridge': 'You were a great friend today!'}]}
