"""Grade 1 English · Q1 W7 D1 · Our Classroom Study Tools.

Source: no DepEd deck/script found in Drive for LANG1Q1W7. Topic from the old Drive lesson
SPT/ENG/GRADE1/Q1/WEEK7/DAY1/INTERACTIVE/index.html: "Our Classroom Study Tools — Short Vowels &
School Objects" (cards book, desk, pencil; value: Pagkamasinop at Pagpapahalaga sa Kagamitan).
The old page was a one-screen stub, so the full lesson is written here.
Week 7 has no verse PNG: Luke 16:10 (taking good care of small things) is used all week.
Objectives: name four school tools; say the five short vowel sounds; listen to
"Tala's New Book" and tell how to take care of our things.
"""

LESSON = {'grade': 1,
 'quarter': 1,
 'week': 7,
 'day': 1,
 'title': 'Our Classroom Study Tools',
 'source': 'Old Drive lesson W7 D1 "Our Classroom Study Tools — Short Vowels & School Objects" '
           '(no DepEd deck found); verse Luke 16:10 chosen for the week',
 'bg': 'media/image10.jpg',
 'next': '../../DAY2/INTERACTIVE/index.html',
 'slides': [{'type': 'cover',
             'pose': 'waving.png',
             'goal': 1,
             'title': 'Our Classroom Study Tools',
             'goals': ['Name 4 school tools', 'Say the 5 short vowels', 'Take care of my things'],
             'say': 'Hello, my friend! (pause) Last week, we retold stories. (pause) Beginning, middle, and '
                    'end! (pause) Today, we go to our classroom. (pause) We meet our study tools!',
             'art': {'file': 'media/art/cover-classroom.png',
                     'prompt': 'A bright Filipino Grade 1 classroom in the morning: Tala (Filipino girl, 6) and '
                               'Bunso (her little brother, 5) in school uniforms waving hello, standing beside '
                               'a wooden desk with a book, a notebook and a yellow pencil on it.',
                     'scene': True}},
            {'id': 'words',
             'type': 'cards',
             'pose': 'pointing.png',
             'goal': 1,
             'title': '4 School Tools',
             'say': 'We use four tools in class every day. (pause) Listen. (pause) Then tap each picture and '
                    'say the word!',
             'yourTurn': 'Tap each picture!',
             'items': [{'word': 'book',
                        'sub': 'we read it',
                        'say': 'Book. (pause) We read stories in a book.',
                        'art': {'file': 'media/art/book.png',
                                'prompt': 'One colourful children\'s storybook lying closed, a picture of a '
                                          'smiling sun on the cover (no letters).'}},
                       {'word': 'notebook',
                        'sub': 'we write in it',
                        'say': 'Notebook. (pause) We write in our notebook.',
                        'art': {'file': 'media/art/notebook.png',
                                'prompt': 'One open lined school notebook with a few simple drawn shapes on '
                                          'the page, no letters.'}},
                       {'word': 'desk',
                        'sub': 'we sit and work here',
                        'say': 'Desk. (pause) We sit and work at our desk.',
                        'art': {'file': 'media/art/desk.png',
                                'prompt': 'One small wooden Filipino classroom desk with a matching chair, '
                                          'empty and clean.'}},
                       {'word': 'pencil',
                        'sub': 'we write with it',
                        'say': 'Pencil. (pause) We write with a pencil.',
                        'art': {'file': 'media/art/pencil.png',
                                'prompt': 'One sharp yellow pencil with a pink eraser on the end, lying '
                                          'diagonally.'}}],
             'bridge': 'Look around a classroom. What do you see?'},
            {'id': 'act',
             'type': 'act',
             'pose': 'clapping.png',
             'goal': 1,
             'title': 'Show Me! Act It Out!',
             'say': 'Let us play! (pause) I say it. (pause) You act it out!',
             'yourTurn': 'Act it out, then tap!',
             'cmds': [{'word': 'Open your book!',
                       'sub': 'Open it wide.',
                       'say': 'Open your book! (pause) Open it wide.',
                       'art': {'file': 'media/art/book.png',
                               'prompt': 'One colourful children\'s storybook lying closed, a picture of a '
                                         'smiling sun on the cover (no letters).'}},
                      {'word': 'Write in your notebook!',
                       'sub': 'Write, write, write.',
                       'say': 'Write in your notebook! (pause) Write, write, write.',
                       'art': {'file': 'media/art/notebook.png',
                               'prompt': 'One open lined school notebook with a few simple drawn shapes on '
                                         'the page, no letters.'}},
                      {'word': 'Hold your pencil!',
                       'sub': 'Hold it gently.',
                       'say': 'Hold your pencil! (pause) Hold it gently.',
                       'art': {'file': 'media/art/pencil.png',
                               'prompt': 'One sharp yellow pencil with a pink eraser on the end, lying '
                                         'diagonally.'}},
                      {'word': 'Sit at your desk!',
                       'sub': 'Sit up tall.',
                       'say': 'Sit at your desk! (pause) Sit up tall.',
                       'art': {'file': 'media/art/desk.png',
                               'prompt': 'One small wooden Filipino classroom desk with a matching chair, '
                                         'empty and clean.'}}],
             'bridge': 'You know the four tools! Now let us use them.'},
            {'id': 'find',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 1,
             'title': 'Listen and Tap!',
             'say': 'Listen carefully. (pause) I say a word. (pause) You tap the right picture.',
             'yourTurn': 'Tap the right picture!',
             'rounds': [{'ask': 'Tap: pencil',
                         'askSay': 'Where is the pencil? Tap it!',
                         'choices': [{'word': 'book',
                                      'art': {'file': 'media/art/book.png',
                                              'prompt': 'One colourful children\'s storybook lying closed, a '
                                                        'picture of a smiling sun on the cover (no letters).'}},
                                     {'word': 'pencil',
                                      'ok': True,
                                      'art': {'file': 'media/art/pencil.png',
                                              'prompt': 'One sharp yellow pencil with a pink eraser on the end, '
                                                        'lying diagonally.'}},
                                     {'word': 'desk',
                                      'art': {'file': 'media/art/desk.png',
                                              'prompt': 'One small wooden Filipino classroom desk with a '
                                                        'matching chair, empty and clean.'}}]},
                        {'ask': 'Tap: notebook',
                         'askSay': 'Where is the notebook? Tap it!',
                         'choices': [{'word': 'notebook',
                                      'ok': True,
                                      'art': {'file': 'media/art/notebook.png',
                                              'prompt': 'One open lined school notebook with a few simple drawn '
                                                        'shapes on the page, no letters.'}},
                                     {'word': 'desk',
                                      'art': {'file': 'media/art/desk.png',
                                              'prompt': 'One small wooden Filipino classroom desk with a '
                                                        'matching chair, empty and clean.'}},
                                     {'word': 'pencil',
                                      'art': {'file': 'media/art/pencil.png',
                                              'prompt': 'One sharp yellow pencil with a pink eraser on the end, '
                                                        'lying diagonally.'}}]}],
             'bridge': 'Great acting! Now let us use our ears.'},
            {'id': 'vowels',
             'type': 'chant',
             'pose': 'clapping.png',
             'goal': 2,
             'title': 'The Short Vowel Song',
             'say': 'Some letters have short sounds. (pause) A, e, i, o, u. (pause) They are vowels! (pause) '
                    'Tap a line and say it with me.',
             'yourTurn': 'Tap a line and say it!',
             'allLabel': 'Say it all!',
             'lines': [{'text': 'a, a, apple!', 'say': 'a, a, apple!'},
                       {'text': 'e, e, egg!', 'say': 'e, e, egg!'},
                       {'text': 'i, i, insect!', 'say': 'i, i, insect!'},
                       {'text': 'o, o, octopus!', 'say': 'o, o, octopus!'},
                       {'text': 'u, u, umbrella!', 'say': 'u, u, umbrella!'}],
             'art': {'file': 'media/art/short-vowels.png',
                     'prompt': 'Five big friendly pictures in a happy row on a sunny classroom wall: a red '
                               'apple, a white egg, a little green insect, a purple octopus, and an open '
                               'yellow umbrella. Tala (Filipino girl, 6) points at them and sings.',
                     'scene': True},
             'bridge': 'Did you hear the short sound in desk? Let us learn more short sounds!'},
            {'id': 'vowel-tap',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 2,
             'title': 'Which Sound Is It?',
             'say': 'Listen to the sound. (pause) Tap the picture that starts with it!',
             'yourTurn': 'Tap the picture!',
             'rounds': [{'ask': 'Which starts with e, e?',
                         'askSay': 'e, e. (pause) Which picture starts with e, e?',
                         'choices': [{'word': 'egg',
                                      'ok': True,
                                      'art': {'file': 'media/art/egg.png',
                                              'prompt': 'One white chicken egg, standing upright.'}},
                                     {'word': 'apple',
                                      'art': {'file': 'media/art/apple.png',
                                              'prompt': 'One shiny red apple with a green leaf.'}},
                                     {'word': 'umbrella',
                                      'art': {'file': 'media/art/umbrella.png',
                                              'prompt': 'One open yellow umbrella.'}}],
                         'yes': 'Yes! e, e, egg!',
                         'yesSay': 'Yes! e, e, egg! (pause) Desk has that sound too. (pause) d, e, sk!'},
                        {'ask': 'Which starts with o, o?',
                         'askSay': 'o, o. (pause) Which picture starts with o, o?',
                         'choices': [{'word': 'insect',
                                      'art': {'file': 'media/art/insect.png',
                                              'prompt': 'One small friendly green insect, like a cute '
                                                        'grasshopper, smiling.'}},
                                     {'word': 'octopus',
                                      'ok': True,
                                      'art': {'file': 'media/art/octopus.png',
                                              'prompt': 'One friendly purple octopus waving with its arms.'}},
                                     {'word': 'egg',
                                      'art': {'file': 'media/art/egg.png',
                                              'prompt': 'One white chicken egg, standing upright.'}}],
                         'yes': 'Yes! o, o, octopus!',
                         'yesSay': 'Yes! o, o, octopus! (pause) You hear the short sounds!'}],
             'bridge': 'Now let us check your ears!'},
            {'id': 's1',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': "Story: Tala's New Book",
             'page': 'Page 1',
             'lines': ['Teacher Ana gives out new books.', 'Tala gets a red book.', 'She smiles. "Thank you!"'],
             'say': "Story time! (pause) Our story is Tala's New Book. (pause) Teacher Ana gives out new books. "
                    '(pause) Tala gets a red book. (pause) Thank you, Teacher Ana!',
             'art': {'file': 'media/art/story-new-book.png',
                     'prompt': 'Filipino Grade 1 classroom: Teacher Ana (kind Filipino woman, 30s, light-blue '
                               'blouse, hair in a bun) handing a shiny new red book to Tala (Filipino girl, 6) '
                               'at her desk; Tala smiling with both hands out; Bunso (5) at the next desk.',
                     'scene': True},
             'bridge': 'You know the vowel sounds! Now let us read a story about a book.'},
            {'id': 's2',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': "Story: Tala's New Book",
             'page': 'Page 2',
             'lines': ['Tala puts the book on her desk.', 'It is snack time.', 'Bunso has a cup of juice.'],
             'say': 'Tala puts her new book on her desk. (pause) It is snack time! (pause) Bunso puts his cup '
                    'of juice on the desk too.',
             'art': {'file': 'media/art/story-snack-time.png',
                     'prompt': 'Snack time in the classroom: the red book lying on Tala\'s desk; Bunso (5) '
                               'putting a full cup of orange juice right next to the book; Tala (6) opening her '
                               'lunch box.',
                     'scene': True},
             'bridge': 'Tala loves her new book. What does she do with it?'},
            {'id': 'mid',
             'type': 'pick',
             'pose': 'raising_hand.png',
             'goal': 3,
             'title': 'Quick! Where Is the Book?',
             'say': 'Quick question!',
             'yourTurn': 'Tap your answer!',
             'rounds': [{'ask': 'Where is the new book?',
                         'askSay': 'Where did Tala put her new book?',
                         'choices': [{'word': 'on the desk',
                                      'ok': True,
                                      'art': {'file': 'media/art/book-on-desk.png',
                                              'prompt': 'A red book lying on a small wooden classroom desk.'}},
                                     {'word': 'under the bed',
                                      'img': '../../../WEEK1/DAY2/INTERACTIVE/media/under-bed.jpg'}],
                         'yes': 'Yes! On the desk.',
                         'yesSay': 'Yes! The book is on the desk. (pause) Next to the juice. (pause) Uh oh!'}],
             'bridge': 'The book and the juice are close together.'},
            {'id': 's3',
             'type': 'story',
             'pose': 'surprised.png',
             'goal': 3,
             'title': "Story: Tala's New Book",
             'page': 'Page 3',
             'lines': ['Oops! Bunso bumps the cup.', 'The juice spills on the desk!', 'It runs to the book!'],
             'say': 'Oops! (pause) Bunso bumps the cup. (pause) The juice spills on the desk! (pause) It runs '
                    'to the new book!',
             'art': {'file': 'media/art/story-spill.png',
                     'prompt': 'Bunso (5) accidentally knocking over his cup; orange juice spilling across the '
                               'desk toward the red book; Tala (6) and Bunso both with surprised faces.',
                     'scene': True},
             'bridge': 'Then something happens!'},
            {'id': 'feel',
             'type': 'pick',
             'pose': 'thinking.png',
             'goal': 3,
             'title': 'How Does Tala Feel?',
             'say': 'The juice runs to her new book. (pause) How does Tala feel?',
             'yourTurn': 'Tap the feeling!',
             'rounds': [{'ask': 'Tala feels...',
                         'askSay': 'How does Tala feel now?',
                         'choices': [{'word': 'worried', 'pose': 'TALA/surprised.png', 'ok': True},
                                     {'word': 'sleepy', 'pose': 'TALA/sitting_lean.png'}],
                         'yes': 'Yes! Tala is worried.',
                         'yesSay': 'Yes! Tala is worried. (pause) What can she do?'}],
             'bridge': 'Oh no! Let us stop and think.'},
            {'id': 's4',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': "Story: Tala's New Book",
             'page': 'Page 4',
             'lines': ['Tala lifts her book. Quick!', 'Bunso wipes the desk.', '"I am sorry, Ate."'],
             'say': 'Quick! (pause) Tala lifts her book up high. (pause) Bunso gets a cloth. (pause) He wipes '
                    'the desk. (pause) I am sorry, Ate, he says.',
             'art': {'file': 'media/art/story-save-book.png',
                     'prompt': 'Tala (6) holding her red book up high and safe; Bunso (5) wiping the spilled '
                               'juice from the desk with a cloth, saying sorry with a shy face.',
                     'scene': True},
             'bridge': 'Tala thinks fast!'},
            {'id': 's5',
             'type': 'story',
             'pose': 'holding_book.png',
             'goal': 3,
             'title': "Story: Tala's New Book",
             'page': 'Page 5',
             'lines': ['The book is clean and dry.', 'Teacher Ana says, "Take care of your things."',
                       'They cover their books.'],
             'say': 'The book is clean and dry! (pause) Teacher Ana smiles. (pause) Take care of your things, '
                    'she says. (pause) Tala and Bunso cover their books.',
             'art': {'file': 'media/art/story-cover-books.png',
                     'prompt': 'Tala (6) and Bunso (5) happily wrapping their books in clear plastic covers at '
                               'a clean desk; Teacher Ana (light-blue blouse, hair in a bun) smiling beside '
                               'them; juice cup now far away on a shelf.',
                     'scene': True},
             'bridge': 'Is the book safe?'},
            {'id': 'order',
             'type': 'order',
             'pose': 'thinking.png',
             'goal': 3,
             'title': 'What Happened First?',
             'say': 'Let us retell the story. (pause) Tap the pictures in order. (pause) Beginning. (pause) '
                    'Middle. (pause) End.',
             'yourTurn': 'Tap what happened first!',
             'slots': ['Beginning', 'Middle', 'End'],
             'items': [{'word': 'Tala gets a book.',
                        'say': 'Beginning: Tala gets a new book.',
                        'art': {'file': 'media/art/story-new-book.png',
                                'prompt': 'Filipino Grade 1 classroom: Teacher Ana (kind Filipino woman, 30s, '
                                          'light-blue blouse, hair in a bun) handing a shiny new red book to '
                                          'Tala (Filipino girl, 6) at her desk; Tala smiling with both hands out; '
                                          'Bunso (5) at the next desk.',
                                'scene': True}},
                       {'word': 'The juice spills.',
                        'say': 'Middle: the juice spills.',
                        'art': {'file': 'media/art/story-spill.png',
                                'prompt': 'Bunso (5) accidentally knocking over his cup; orange juice spilling '
                                          'across the desk toward the red book; Tala (6) and Bunso both with '
                                          'surprised faces.',
                                'scene': True}},
                       {'word': 'The book is safe.',
                        'say': 'End: the book is safe and covered.',
                        'art': {'file': 'media/art/story-cover-books.png',
                                'prompt': 'Tala (6) and Bunso (5) happily wrapping their books in clear plastic '
                                          'covers at a clean desk; Teacher Ana (light-blue blouse, hair in a '
                                          'bun) smiling beside them; juice cup now far away on a shelf.',
                                'scene': True}}],
             'ask': ['What happened at the beginning?', 'What happened in the middle?', 'What happened at the end?'],
             'yes': 'Beginning, middle, end. You did it!',
             'yesSay': 'Beginning, middle, end! (pause) You retold the whole story!',
             'bridge': 'That is the end of the story. Can you retell it?'},
            {'id': 'my-care',
             'type': 'sentence',
             'pose': 'point_self.png',
             'goal': 3,
             'title': 'I Take Care of My...',
             'say': 'Tala takes care of her book. (pause) What do you take care of? (pause) Tap one. (pause) '
                    'Then say it with me.',
             'yourTurn': 'Tap one and say it!',
             'pre': 'I take care of my',
             'post': '.',
             'options': [{'word': 'book',
                          'art': {'file': 'media/art/book.png',
                                  'prompt': 'One colourful children\'s storybook lying closed, a picture of a '
                                            'smiling sun on the cover (no letters).'}},
                         {'word': 'notebook',
                          'art': {'file': 'media/art/notebook.png',
                                  'prompt': 'One open lined school notebook with a few simple drawn shapes on '
                                            'the page, no letters.'}},
                         {'word': 'pencil',
                          'art': {'file': 'media/art/pencil.png',
                                  'prompt': 'One sharp yellow pencil with a pink eraser on the end, lying '
                                            'diagonally.'}},
                         {'word': 'desk',
                          'art': {'file': 'media/art/desk.png',
                                  'prompt': 'One small wooden Filipino classroom desk with a matching chair, '
                                            'empty and clean.'}}],
             'bridge': 'Tala and Bunso take care of their books. What about you?'},
            {'id': 'talk',
             'type': 'talk',
             'pose': 'talking.png',
             'goal': 1,
             'title': 'Your Turn to Talk!',
             'say': 'Show me one of your school tools. (pause) Say: This is my pencil. (pause) I write with it. '
                    '(pause) Your turn!',
             'yourTurn': 'Say it out loud!',
             'frame': 'This is my ____. I ____ with it.',
             'example': {'label': 'Tala says', 'text': 'This is my pencil. I write with it.'},
             'art': {'file': 'media/art/talk-my-pencil.png',
                     'prompt': 'Tala (Filipino girl, 6) at her desk proudly holding up her yellow pencil to show '
                               'it, her notebook open in front of her, happy face.'},
             'bridge': 'Now show me YOUR school tool!'},
            {'id': 'verse',
             'type': 'verse',
             'pose': 'praying.png',
             'verse': 'Whoever can be trusted with very little can also be trusted with much.',
             'ref': 'Luke 16:10',
             'meaning': 'Take good care of small things, like your book and pencil.',
             'say': 'Our Bible verse is about small things. (pause) Take good care of them, like Tala did. '
                    '(pause) Then God can trust you with big things!',
             'verseSay': 'Whoever can be trusted with very little (pause) can also be trusted with much. '
                         '(pause) Luke sixteen, verse ten.',
             'art': {'file': 'media/art/verse-care.png',
                     'prompt': 'Tala (6) and Bunso (5) carefully putting their covered books, notebooks and '
                               'pencils neatly into their school bags at a tidy classroom desk, warm golden '
                               'light, gentle happy faces.',
                     'scene': True},
             'bridge': 'Tala took care of her book. The Bible tells us why that matters.'},
            {'id': 'done',
             'type': 'celebrate',
             'pose': 'clapping.png',
             'title': 'Great Job, Tool Keeper!',
             'recap': ['I know: book, notebook, desk, pencil.',
                       'I can say a, e, i, o, u.',
                       'I take care of my things.'],
             'say': 'Hooray! (pause) You named four school tools. (pause) You said the short vowels. (pause) '
                    'And you take care of your things! (pause) Tomorrow, we draw with paper, an eraser, and a '
                    'ruler!',
             'bridge': 'You worked so hard today!'}]}
